"use client";

import { useState } from "react";
import { GraduationCap, ShieldCheck, Users } from "lucide-react";

type AuthMode = "login" | "register" | "admin_setup";

export default function AuthForm({ returnTo }: { returnTo: string }) {
  const portal = (() => { try { const value = new URL(returnTo, "https://app.local").searchParams.get("portal"); return value === "admin" || value === "facilitator" || value === "learner" ? value : "learner"; } catch { return "learner"; } })();
  const [mode, setMode] = useState<AuthMode>("login"); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const selectMode = (nextMode: AuthMode) => { setMode(nextMode); setError(""); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch("/api/render-auth", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, fullName, email, password, returnTo }) }); const result = await response.json() as { error?: string; returnTo?: string }; if (!response.ok) throw new Error(result.error ?? "Authentication failed."); window.location.assign(result.returnTo ?? "/"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Authentication failed."); } finally { setLoading(false); } };
  const isAdmin = portal === "admin"; const isFacilitator = portal === "facilitator"; const creating = mode !== "login";
  const heading = mode === "admin_setup" ? "Create the first administrator password." : mode === "register" ? "Create your learner account." : isAdmin ? "System administrator sign in." : isFacilitator ? "Facilitator sign in." : "Learner sign in.";
  const description = mode === "admin_setup" ? "Use the email configured as INITIAL_ADMIN_EMAIL on Render. This one-time setup creates its secure sign-in credentials." : mode === "register" ? "After account creation, complete your biodata, national ID and live-selfie verification." : isAdmin ? "Only the email configured as the initial administrator can open the administration portal." : isFacilitator ? "Use the institutional email and permanent password linked to your administrator-issued invitation." : "Use your learner account, or choose New learner to register.";
  return <main className="access-shell render-auth-shell"><section className="access-card render-auth-card"><div className="access-brand"><div className="brand-mark"><GraduationCap size={28} /></div><div><strong>UCC Microcredentials</strong><span>University of Cape Coast</span></div></div><div className={`auth-portal-badge ${portal}`}>{isAdmin ? <Users /> : <ShieldCheck />}<span>{isAdmin ? "SYSTEM ADMINISTRATION" : isFacilitator ? "FACILITATOR PORTAL" : "LEARNER PORTAL"}</span></div><h1>{heading}</h1><p>{description}</p><div className="auth-mode"><button type="button" className={mode === "login" ? "active" : ""} onClick={() => selectMode("login")}>{isAdmin ? "Admin sign in" : "Sign in"}</button>{isAdmin ? <button type="button" className={mode === "admin_setup" ? "active" : ""} onClick={() => selectMode("admin_setup")}>First admin setup</button> : !isFacilitator && <button type="button" className={mode === "register" ? "active" : ""} onClick={() => selectMode("register")}>New learner</button>}</div><form className="render-auth-form" onSubmit={submit}>{creating && <label>Full legal name<input value={fullName} onChange={(event) => setFullName(event.target.value)} autoComplete="name" required /></label>}<label>{isAdmin ? "Administrator email" : "Email address"}<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /></label><label>{mode === "admin_setup" ? "Create password" : "Password"}<input type="password" minLength={10} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={mode === "login" ? "current-password" : "new-password"} required /><span>Minimum 10 characters</span></label>{error && <div className="auth-error">{error}</div>}<button className={`access-primary ${isAdmin ? "admin-submit" : ""}`} disabled={loading}>{isAdmin ? <Users size={18} /> : <ShieldCheck size={18} />} {loading ? "Please wait…" : mode === "admin_setup" ? "Create administrator access" : mode === "register" ? "Create learner account" : isAdmin ? "Open administration portal" : "Sign in securely"}</button></form><a className="access-secondary" href="/">Return to portal selection</a><small>Passwords are salted and hashed. Role permissions are checked separately after sign-in.</small></section></main>;
}
