import { credentialEvidenceValid, reviewAffectedCredential } from "@/lib/grading-workflow";
import { getRawDb } from "@/db/raw";
import { requireActiveProfile } from "@/lib/accounts";
import { coursePermission, enrolledCourse, parseRecord, recordEngagement } from "@/lib/course-access";
import { learnerCourseRecord, usageReport } from "@/lib/delivery-reports";
import { notify, notifyCourse, notifyTeachers } from "@/lib/delivery-notifications";
import { rejectCrossSiteMutation } from "@/lib/request-security";
import { recordAudit } from "@/lib/audit";
import { issueCertificateIfComplete } from "@/lib/course-completion";
import { normalizeCourseDesign } from "@/lib/course-design";

const clean=(v:unknown,n=2000)=>String(v??"").trim().slice(0,n);
const validUrl=(v:unknown)=>{try{const url=new URL(String(v));return ["https:","http:"].includes(url.protocol)?url.href:"";}catch{return "";}};
const bad=(message:string,status=400)=>Response.json({error:message},{status});
export async function GET(request:Request) {
  const account=await requireActiveProfile();if(account.error||!account.profile)return account.error;
  const profile=account.profile,db=getRawDb(),p=new URL(request.url).searchParams,area=p.get("area")||"overview",code=clean(p.get("courseCode"),120),before=Number(p.get("before"))||Number.MAX_SAFE_INTEGER,offset=Math.max(0,Number(p.get("offset"))||0);
  const courses=await db.prepare(`SELECT c.code,c.title,c.status FROM course_drafts c WHERE ${profile.role==="learner"?"EXISTS(SELECT 1 FROM enrollments e WHERE e.course_code=c.code AND e.user_email=? AND e.status IN ('active','completed'))":"(c.created_by_email=? OR ?='admin' OR EXISTS(SELECT 1 FROM course_team t WHERE t.course_code=c.code AND t.user_email=?))"} ORDER BY c.title LIMIT 200`).bind(...(profile.role==="learner"?[profile.email]:[profile.email,profile.role,profile.email])).all<{code:string;title:string;status:string}>();
  if(code&&!await coursePermission(profile,code))return bad("You do not have access to this course.",403);
  const base={courses:courses.results,permissions:code?{teach:await coursePermission(profile,code,"teach"),manage:await coursePermission(profile,code,"manage"),mark:await coursePermission(profile,code,"mark"),moderate:await coursePermission(profile,code,"moderate")}:null};
  if(area==="overview"||area==="assessments") {
    if(profile.role==="learner") {const records=[];for(const c of courses.results)records.push(await learnerCourseRecord(profile.email,c.code));return Response.json({...base,records:records.filter(Boolean)});}
    const stats=[];
    for(const c of courses.results) {
      const designRow=await db.prepare("SELECT design_json FROM course_drafts WHERE code=?").bind(c.code).first<{design_json:string}>(),design=normalizeCourseDesign(parseRecord(designRow?.design_json,{}));
      const row=await db.prepare(`SELECT (SELECT COUNT(*) FROM assessment_submissions WHERE course_code=? AND status IN ('submitted','awaiting_marking')) pending,(SELECT COUNT(*) FROM assessment_submissions WHERE course_code=? AND status IN ('submitted','awaiting_marking') AND datetime(submitted_at)<datetime('now',?)) overdue,(SELECT COUNT(*) FROM enrollments e WHERE e.course_code=? AND e.status='active' AND datetime(e.enrolled_at)<datetime('now','-14 days') AND NOT EXISTS(SELECT 1 FROM engagement_events a WHERE a.user_email=e.user_email AND a.course_code=e.course_code AND datetime(a.created_at)>datetime('now','-14 days'))) at_risk,(SELECT COUNT(*) FROM course_posts p WHERE p.course_code=? AND p.parent_id IS NULL AND p.kind='discussion' AND p.hidden=0 AND NOT EXISTS(SELECT 1 FROM course_posts r WHERE r.parent_id=p.id AND r.hidden=0)) unanswered`).bind(c.code,c.code,`-${design.delivery.feedbackDays} days`,c.code,c.code).first();
      stats.push({...c,...row});
    }
    return Response.json({...base,queues:stats});
  }
  if(area==="workspace") {if(profile.role!=="learner"||!code)return bad("Select an enrolled course.");const rows=await db.prepare("SELECT item_key,value_json,updated_at FROM learner_workspace WHERE user_email=? AND course_code=?").bind(profile.email,code).all<{item_key:string;value_json:string;updated_at:string}>();return Response.json({...base,items:rows.results.map(r=>({...r,value:parseRecord(r.value_json,null)}))});}
  if(area==="preferences")return Response.json({preferences:await db.prepare("SELECT * FROM notification_preferences WHERE user_email=?").bind(profile.email).first()??{assessment_reminders:1,session_reminders:1,teaching_alerts:1,weekly_digest:0,email_enabled:0}});
  if(area==="notifications") {const rows=await db.prepare("SELECT * FROM delivery_notifications WHERE user_email=? AND id<? ORDER BY id DESC LIMIT 101").bind(profile.email,before).all<{id:number}>();return Response.json({items:rows.results.slice(0,100),nextCursor:rows.results.length>100?rows.results[99].id:null});}
  if(area==="posts") {if(!code)return Response.json({...base,items:[]});const rows=await db.prepare("SELECT p.*,u.full_name author_name FROM course_posts p LEFT JOIN users u ON u.email=p.author_email WHERE p.course_code=? AND p.hidden=0 AND p.id<? ORDER BY p.id DESC LIMIT 101").bind(code,before).all<{id:number}>();return Response.json({...base,items:rows.results.slice(0,100),nextCursor:rows.results.length>100?rows.results[99].id:null});}
  if(area==="sessions") {
    const rows=await db.prepare(`SELECT s.*,a.attended FROM delivery_sessions s LEFT JOIN session_attendance a ON a.session_id=s.id AND a.user_email=? WHERE (?='' OR s.course_code=?) AND s.cancelled=0 AND ${profile.role==="learner"?"EXISTS(SELECT 1 FROM enrollments e WHERE e.course_code=s.course_code AND e.user_email=? AND e.status IN ('active','completed'))":"EXISTS(SELECT 1 FROM course_drafts c WHERE c.code=s.course_code AND (c.created_by_email=? OR ?='admin' OR EXISTS(SELECT 1 FROM course_team t WHERE t.course_code=c.code AND t.user_email=?)))"} ORDER BY s.starts_at DESC LIMIT 100 OFFSET ?`).bind(profile.email,code,code,...(profile.role==="learner"?[profile.email]:[profile.email,profile.role,profile.email]),offset).all();return Response.json({...base,items:rows.results,nextOffset:rows.results.length===100?offset+100:null});
  }
  if(area==="teams"||area==="cohorts"||area==="gradebook") {
    if(profile.role==="learner")return bad("Teaching access is required.",403);
    if(!code)return Response.json({...base,items:[]});
    const team=await db.prepare("SELECT t.*,u.full_name FROM course_team t JOIN users u ON u.email=t.user_email WHERE t.course_code=?").bind(code).all();
    const cohorts=await db.prepare("SELECT c.*,COUNT(m.user_email) members FROM course_cohorts c LEFT JOIN cohort_members m ON m.cohort_id=c.id WHERE c.course_code=? GROUP BY c.id").bind(code).all();
    const runs=await db.prepare("SELECT * FROM course_runs WHERE base_code=? OR offering_code=? ORDER BY id DESC").bind(code,code).all();
    const learners=await db.prepare(`SELECT e.id,e.user_email,u.full_name,e.status,e.enrolled_at,a.score,a.passed,(SELECT MAX(created_at) FROM engagement_events WHERE user_email=e.user_email AND course_code=e.course_code) last_activity,(SELECT group_concat(c.name,', ') FROM cohort_members m JOIN course_cohorts c ON c.id=m.cohort_id WHERE m.user_email=e.user_email AND c.course_code=e.course_code) cohorts FROM enrollments e JOIN users u ON u.email=e.user_email LEFT JOIN assessment_attempts a ON a.user_email=e.user_email AND a.course_code=e.course_code WHERE e.course_code=? AND e.id<? ORDER BY e.id DESC LIMIT 101`).bind(code,before).all<{id:number;user_email:string}>();
    const items=[];for(const learner of learners.results.slice(0,100))items.push({...learner,...(area==="gradebook"?{record:await learnerCourseRecord(learner.user_email,code)}:{})});
    const appeals=await db.prepare("SELECT a.*,s.course_code FROM assessment_appeals a JOIN assessment_submissions s ON s.id=a.submission_id WHERE s.course_code=? ORDER BY a.id DESC LIMIT 100").bind(code).all();
    const evaluations=await db.prepare("SELECT rating,feedback,updated_at FROM course_evaluations WHERE course_code=? ORDER BY updated_at DESC LIMIT 100").bind(code).all();
    return Response.json({...base,items,team:team.results,cohorts:cohorts.results,runs:runs.results,appeals:appeals.results,evaluations:evaluations.results,nextCursor:learners.results.length>100?learners.results[99].id:null});
  }
  if(area==="assessment-history") {const id=Number(p.get("id")),submission=await db.prepare("SELECT user_email,course_code FROM assessment_submissions WHERE id=?").bind(id).first<{user_email:string;course_code:string}>();if(!submission||(profile.role==="learner"?submission.user_email!==profile.email:!await coursePermission(profile,submission.course_code)))return bad("Submission not found.",404);return Response.json({history:(await db.prepare("SELECT * FROM grade_history WHERE submission_id=? ORDER BY id DESC").bind(id).all()).results,appeals:(await db.prepare("SELECT * FROM assessment_appeals WHERE submission_id=? ORDER BY id DESC").bind(id).all()).results});}
  if(area==="payments") {const rows=await db.prepare(`SELECT o.reference,o.course_code,o.purpose,o.amount_pesewas,o.currency,o.status,o.paid_at,o.created_at,r.status refund_status,r.response refund_response FROM payment_orders o LEFT JOIN refund_requests r ON r.payment_reference=o.reference WHERE (?='admin' OR o.user_email=?) ORDER BY o.id DESC LIMIT 100 OFFSET ?`).bind(profile.role,profile.email,offset).all();return Response.json({...base,items:rows.results,refunds:profile.role==="admin"?(await db.prepare("SELECT * FROM refund_requests ORDER BY id DESC LIMIT 100").all()).results:[],nextOffset:rows.results.length===100?offset+100:null});}
  if(area==="usage") {if(profile.role!=="admin")return bad("Administrator access is required.",403);const month=p.get("month")||new Date().toISOString().slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))return bad("Choose a valid billing month.");return Response.json({report:await usageReport(month),frozen:await db.prepare("SELECT * FROM usage_invoice_snapshots WHERE month=?").bind(month).first()});}
  if(area==="credential-reviews") {if(profile.role!=="admin")return bad("Administrator access is required.",403);return Response.json({items:(await db.prepare("SELECT r.*,c.learner_name,c.course_code,c.status credential_status FROM credential_reviews r JOIN certificates c ON c.certificate_code=r.certificate_code ORDER BY r.id DESC LIMIT 100").all()).results});}
  if(area==="recovery") {if(profile.role==="learner")return bad("Teaching access is required.",403);return Response.json({items:(await db.prepare("SELECT draft_key,payload_json,updated_at FROM studio_recovery WHERE user_email=? ORDER BY updated_at DESC LIMIT 20").bind(profile.email).all()).results});}
  return bad("Unknown delivery area.");
}

export async function POST(request:Request) {
  const origin=rejectCrossSiteMutation(request);if(origin)return origin;
  const account=await requireActiveProfile();if(account.error||!account.profile)return account.error;
  const profile=account.profile,db=getRawDb(),p=await request.json() as Record<string,unknown>,action=clean(p.action,80),code=clean(p.courseCode,120);
  if(code&&!await coursePermission(profile,code))return bad("Course access is required.",403);
  const teach=async(permission:"teach"|"manage"|"moderate"|"mark"="teach")=>profile.role!=="learner"&&Boolean(code)&&await coursePermission(profile,code,permission);
  let result:Record<string,unknown>={saved:true};
  if(action==="preferences") {const bool=(key:string)=>p[key]===true||p[key]===1?1:0;await db.prepare("INSERT INTO notification_preferences(user_email,assessment_reminders,session_reminders,teaching_alerts,weekly_digest,email_enabled) VALUES(?,?,?,?,?,?) ON CONFLICT(user_email) DO UPDATE SET assessment_reminders=excluded.assessment_reminders,session_reminders=excluded.session_reminders,teaching_alerts=excluded.teaching_alerts,weekly_digest=excluded.weekly_digest,email_enabled=excluded.email_enabled").bind(profile.email,bool("assessment_reminders"),bool("session_reminders"),bool("teaching_alerts"),bool("weekly_digest"),bool("email_enabled")).run();}
  else if(action==="read-notifications")await db.prepare("UPDATE delivery_notifications SET read_at=CURRENT_TIMESTAMP WHERE user_email=? AND (?=0 OR id=?)").bind(profile.email,Number(p.id)||0,Number(p.id)||0).run();
  else if(action==="retry-email")await db.prepare("UPDATE delivery_notifications SET email_status='pending' WHERE user_email=? AND id=? AND email_status='failed'").bind(profile.email,Number(p.id)).run();
  else if(action==="workspace") {if(profile.role!=="learner"||!code)return bad("An enrolled course is required.",403);const key=clean(p.key,200),value=JSON.stringify(p.value??null);if(!key||value.length>200000)return bad("The saved item is too large or has no name.");await db.prepare("INSERT INTO learner_workspace(user_email,course_code,item_key,value_json) VALUES(?,?,?,?) ON CONFLICT(user_email,course_code,item_key) DO UPDATE SET value_json=excluded.value_json,updated_at=CURRENT_TIMESTAMP").bind(profile.email,code,key,value).run();}
  else if(action==="recovery") {if(profile.role==="learner")return bad("Teaching access is required.",403);const key=clean(p.key,120),value=JSON.stringify(p.value??{});if(!key||value.length>2000000)return bad("Draft recovery data is invalid.");await db.prepare("INSERT INTO studio_recovery(user_email,draft_key,payload_json) VALUES(?,?,?) ON CONFLICT(user_email,draft_key) DO UPDATE SET payload_json=excluded.payload_json,updated_at=CURRENT_TIMESTAMP").bind(profile.email,key,value).run();}
  else if(action==="post") {
    const message=clean(p.message,5000),title=clean(p.title,200),kind=p.kind==="announcement"?"announcement":"discussion",parent=Number(p.parentId)||null;
    if(!code||message.length<3||(!parent&&!title))return bad("Choose a course and enter a title and message.");
    if(kind==="announcement"&&!await teach())return bad("Only the teaching team can publish an announcement.",403);
    if(parent&&!await db.prepare("SELECT id FROM course_posts WHERE id=? AND course_code=? AND hidden=0").bind(parent,code).first())return bad("The discussion does not exist.",404);
    const created=await db.prepare("INSERT INTO course_posts(course_code,parent_id,author_email,kind,title,message) VALUES(?,?,?,?,?,?)").bind(code,parent,profile.email,kind,title,message).run();
    if(kind==="announcement")await notifyCourse(code,`post-${created.meta.last_row_id}`,"announcement",title,message);else await notifyTeachers(code,`post-${created.meta.last_row_id}`,"New course discussion",message);
  }
  else if(action==="moderate-post") {if(!await teach("moderate"))return bad("Course moderation permission is required.",403);await db.prepare("UPDATE course_posts SET hidden=? WHERE id=? AND course_code=?").bind(p.hidden?1:0,Number(p.id),code).run();}
  else if(action==="session") {
    if(!await teach())return bad("Course teaching permission is required.",403);
    const title=clean(p.title,200),start=Date.parse(String(p.startsAt)),end=Date.parse(String(p.endsAt)),url=validUrl(p.meetingUrl),recording=p.recordingUrl?validUrl(p.recordingUrl):"";
    if(!title||!Number.isFinite(start)||!Number.isFinite(end)||end<=start||!url||(p.recordingUrl&&!recording))return bad("Enter a title, valid start and end times, and a meeting link.");
    const id=Number(p.id);
    if(id){const update=await db.prepare("UPDATE delivery_sessions SET title=?,starts_at=?,ends_at=?,meeting_url=?,recording_url=?,attendance_required=? WHERE id=? AND course_code=?").bind(title,new Date(start).toISOString(),new Date(end).toISOString(),url,recording,p.attendanceRequired===false?0:1,id,code).run();if(!update.meta.changes)return bad("Session not found.",404);}
    else {const created=await db.prepare("INSERT INTO delivery_sessions(course_code,title,starts_at,ends_at,meeting_url,recording_url,attendance_required,created_by) VALUES(?,?,?,?,?,?,?,?)").bind(code,title,new Date(start).toISOString(),new Date(end).toISOString(),url,recording,p.attendanceRequired===false?0:1,profile.email).run();result.id=Number(created.meta.last_row_id);}
    await notifyCourse(code,`session-${id||result.id}-${Date.now()}`,"session","Live session schedule updated",`${title}: ${new Date(start).toUTCString()}`);
  }
  else if(action==="cancel-session") {if(!await teach())return bad("Teaching permission is required.",403);await db.prepare("UPDATE delivery_sessions SET cancelled=1 WHERE id=? AND course_code=?").bind(Number(p.id),code).run();await notifyCourse(code,`cancel-${p.id}`,"session","Live session cancelled",`Session ${p.id} has been cancelled.`);}
  else if(action==="attendance") {
    if(!await teach())return bad("Teaching permission is required.",403);
    const email=clean(p.email,254).toLowerCase(),session=Number(p.sessionId);
    const scheduled = await db.prepare("SELECT ends_at FROM delivery_sessions WHERE id=? AND course_code=? AND cancelled=0").bind(session,code).first<{ends_at:string}>();
    if(!scheduled||!await enrolledCourse(email,code))return bad("Choose an enrolled learner and this course's session.");
    if(p.attended!==false&&Date.parse(scheduled.ends_at)>Date.now())return bad("Record attendance after the session has ended.",409);
    await db.prepare("INSERT INTO session_attendance(session_id,user_email,attended,recorded_by) VALUES(?,?,?,?) ON CONFLICT(session_id,user_email) DO UPDATE SET attended=excluded.attended,recorded_by=excluded.recorded_by,recorded_at=CURRENT_TIMESTAMP").bind(session,email,p.attended===false?0:1,profile.email).run();
    await reviewAffectedCredential(email,code,"The teaching team corrected the attendance record.");
    await issueCertificateIfComplete(email,code);
  }
  else if(action==="team") {
    if(!await teach("manage"))return bad("Only the course owner or administrator can assign the team.",403);
    const email=clean(p.email,254).toLowerCase(),role=clean(p.role,30);
    if(!await db.prepare("SELECT email FROM users WHERE email=? AND role='facilitator' AND status='active'").bind(email).first()||!["cofacilitator","marker","moderator","remove"].includes(role))return bad("Choose an active facilitator account and a team role.");
    if(role==="remove")await db.prepare("DELETE FROM course_team WHERE course_code=? AND user_email=?").bind(code,email).run();else await db.prepare("INSERT INTO course_team(course_code,user_email,team_role,assigned_by) VALUES(?,?,?,?) ON CONFLICT(course_code,user_email) DO UPDATE SET team_role=excluded.team_role,assigned_by=excluded.assigned_by").bind(code,email,role,profile.email).run();
  }
  else if(action==="cohort") {if(!await teach())return bad("Teaching permission is required.",403);const name=clean(p.name,100);if(!name)return bad("Enter a cohort name.");await db.prepare("INSERT OR IGNORE INTO course_cohorts(course_code,name) VALUES(?,?)").bind(code,name).run();}
  else if(action==="cohort-member") {if(!await teach())return bad("Teaching permission is required.",403);const email=clean(p.email,254).toLowerCase(),id=Number(p.cohortId);if(!await enrolledCourse(email,code)||!await db.prepare("SELECT id FROM course_cohorts WHERE id=? AND course_code=?").bind(id,code).first())return bad("Choose this course's cohort and enrolled learner.");if(p.remove)await db.prepare("DELETE FROM cohort_members WHERE cohort_id=? AND user_email=?").bind(id,email).run();else await db.prepare("INSERT OR IGNORE INTO cohort_members(cohort_id,user_email) VALUES(?,?)").bind(id,email).run();}
  else if(action==="run") {
    if(!await teach("manage"))return bad("The course owner or administrator must create a new run.",403);
    const name=clean(p.name,100),offering=clean(p.offeringCode,121).toUpperCase(),start=Date.parse(String(p.startsAt)),end=Date.parse(String(p.endsAt)),close=p.enrolmentClosesAt?Date.parse(String(p.enrolmentClosesAt)):start;
    if(!name||!/^[-A-Z0-9_]{3,80}$/.test(offering)||!Number.isFinite(start)||!Number.isFinite(end)||end<=start||!Number.isFinite(close)||close>end)return bad("Enter a unique offering code (3 to 80 characters), intake name and valid dates.");
    try {result=db.transaction(native=>{
      const course=native.prepare("SELECT * FROM course_drafts WHERE code=? AND status='active' LIMIT 1").get(code) as Record<string,unknown>|undefined;if(!course)throw new Error("Create intakes from an approved active course.");
      if(native.prepare("SELECT id FROM course_drafts WHERE code=?").get(offering))throw new Error("That offering code is already used.");
      const keys=Object.keys(course).filter(key=>!["id","code","title","created_at","updated_at"].includes(key));
      native.prepare(`INSERT INTO course_drafts(code,title,${keys.join(",")}) VALUES(${Array(keys.length+2).fill("?").join(",")})`).run(offering,`${course.title} · ${name}`,...keys.map(key=>course[key] as string|number|null));
      native.prepare("INSERT INTO course_runs(base_code,offering_code,name,starts_at,ends_at,enrolment_closes_at,capacity,created_by) VALUES(?,?,?,?,?,?,?,?)").run(code,offering,name,new Date(start).toISOString(),new Date(end).toISOString(),new Date(close).toISOString(),Math.max(0,Math.floor(Number(p.capacity)||0)),profile.email);
      native.prepare("INSERT INTO course_team(course_code,user_email,team_role,assigned_by) SELECT ?,user_email,team_role,assigned_by FROM course_team WHERE course_code=?").run(offering,code);
      const assignments=native.prepare("SELECT * FROM colab_assignments WHERE course_code=? AND status='active'").all(code) as Record<string,unknown>[];
      for(const item of assignments){const columns=Object.keys(item).filter(k=>!["id","course_code","created_at","updated_at"].includes(k));native.prepare(`INSERT INTO colab_assignments(course_code,${columns.join(",")}) VALUES(${Array(columns.length+1).fill("?").join(",")})`).run(offering,...columns.map(k=>item[k] as string|number|null));}
      return {saved:true,offeringCode:offering};
    });}catch(error){return bad(error instanceof Error?error.message:"The intake could not be created.",409);}
  }
  else if(action==="appeal") {const id=Number(p.submissionId),reason=clean(p.reason,5000);if(profile.role!=="learner"||reason.length<10||!await db.prepare("SELECT id FROM assessment_submissions WHERE id=? AND user_email=? AND status IN ('marked','resubmit')").bind(id,profile.email).first())return bad("Choose a decided assessment and explain your appeal.");const row=await db.prepare("SELECT course_code FROM assessment_submissions WHERE id=?").bind(id).first<{course_code:string}>();if(await db.prepare("SELECT id FROM assessment_appeals WHERE submission_id=? AND status='open'").bind(id).first())return bad("An appeal is already open for this submission.",409);await db.prepare("INSERT INTO assessment_appeals(submission_id,user_email,reason) VALUES(?,?,?)").bind(id,profile.email,reason).run();await notifyTeachers(row!.course_code,`appeal-${id}`,"Assessment appeal submitted",reason);}
  else if(action==="appeal-decision") {const id=Number(p.id),row=await db.prepare("SELECT a.*,s.course_code FROM assessment_appeals a JOIN assessment_submissions s ON s.id=a.submission_id WHERE a.id=?").bind(id).first<{course_code:string;user_email:string}>();if(!row||!await coursePermission(profile,row.course_code,"moderate"))return bad("Moderation permission is required.",403);const response=clean(p.response,5000);if(response.length<10)return bad("Record an appeal response. Grade changes must be recorded separately in the gradebook.");await db.prepare("UPDATE assessment_appeals SET status='resolved',response=?,decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?").bind(response,profile.email,id).run();await notify(row.user_email,`appeal-decision-${id}`,"assessment","Appeal response available",response,"/?view=assessments");}
  else if(action==="retry-grading") {const id=Number(p.id),row=await db.prepare("SELECT course_code FROM assessment_submissions WHERE id=?").bind(id).first<{course_code:string}>();if(!row||!await coursePermission(profile,row.course_code,"mark"))return bad("Marking permission is required.",403);const changed=db.transaction(native=>{const job=native.prepare("UPDATE grading_jobs SET state='queued',attempts=0,next_attempt_at=CURRENT_TIMESTAMP,last_error=NULL WHERE submission_id=? AND state='failed'").run(id);if(job.changes)native.prepare("UPDATE assessment_submissions SET status='submitted' WHERE id=? AND status='awaiting_marking'").run(id);return Number(job.changes);});if(!changed)return bad("Only failed grading jobs can be retried.",409);}
  else if(action==="evaluation") {if(profile.role!=="learner"||!await enrolledCourse(profile.email,code))return bad("Enrolment is required.",403);const rating=Number(p.rating);if(!Number.isInteger(rating)||rating<1||rating>5)return bad("Choose a rating between 1 and 5.");await db.prepare("INSERT INTO course_evaluations(user_email,course_code,rating,feedback) VALUES(?,?,?,?) ON CONFLICT(user_email,course_code) DO UPDATE SET rating=excluded.rating,feedback=excluded.feedback,updated_at=CURRENT_TIMESTAMP").bind(profile.email,code,rating,clean(p.feedback,5000)).run();await recordEngagement(profile.email,code,"evaluation");}
  else if(action==="refund-request") {const reference=clean(p.reference,120),reason=clean(p.reason,5000),order=await db.prepare("SELECT course_code FROM payment_orders WHERE reference=? AND user_email=? AND status='paid'").bind(reference,profile.email).first<{course_code:string}>();if(!order||reason.length<10)return bad("Choose your paid order and give a refund reason.");try{await db.prepare("INSERT INTO refund_requests(payment_reference,user_email,reason) VALUES(?,?,?)").bind(reference,profile.email,reason).run();}catch{return bad("A refund request already exists for this payment.",409);}}
  else if(action==="refund-decision") {if(profile.role!=="admin")return bad("Administrator access is required.",403);const status=clean(p.status,30),response=clean(p.response,5000);if(!["approved","rejected","completed"].includes(status)||response.length<10||(status==="completed"&&!clean(p.externalReference)))return bad("Record the decision and, for a completed refund, the payment provider refund reference.");await db.prepare("UPDATE refund_requests SET status=?,response=?,external_reference=?,decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,response,clean(p.externalReference,200)||null,profile.email,Number(p.id)).run();}
  else if(action==="billing-settings"||action==="freeze-usage"||action==="test-account") {if(profile.role!=="admin")return bad("Administrator access is required.",403);if(action==="billing-settings"){const rate=Number(p.rateGhs);if(!Number.isFinite(rate)||rate<0||!["engaged","enrolled"].includes(String(p.definition)))return bad("Choose a billing definition and a non-negative per-user rate.");await db.prepare("INSERT INTO platform_settings(setting_key,setting_value,updated_by_email) VALUES('usage_billing',?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_by_email=excluded.updated_by_email,updated_at=CURRENT_TIMESTAMP").bind(JSON.stringify({definition:p.definition,rateGhs:rate}),profile.email).run();}else if(action==="test-account")await db.prepare("UPDATE users SET is_test_record=? WHERE email=? AND role='learner'").bind(p.isTest?1:0,clean(p.email,254).toLowerCase()).run();else {const month=clean(p.month,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))return bad("Choose a valid month.");const report=await usageReport(month);try{await db.prepare("INSERT INTO usage_invoice_snapshots(month,definition,report_json,created_by) VALUES(?,?,?,?)").bind(month,report.definition,JSON.stringify(report),profile.email).run();}catch{return bad("This month's reconciliation is already frozen.",409);}}}
  else if(action==="credential-review") {if(profile.role!=="admin")return bad("Administrator access is required.",403);const id=Number(p.id),decision=clean(p.decision,30),reason=clean(p.reason,5000),review=await db.prepare("SELECT r.certificate_code,c.user_email,c.course_code FROM credential_reviews r JOIN certificates c ON c.certificate_code=r.certificate_code WHERE r.id=? AND r.status='open'").bind(id).first<{certificate_code:string;user_email:string;course_code:string}>();if(!review||!["restore","revoke"].includes(decision)||reason.length<10)return bad("Choose an open review, decision and reason.");if(decision==="restore"&&!await credentialEvidenceValid(review.certificate_code))return bad("The corrected completion requirements are still unmet. Restore only after the learning evidence is valid.",409);db.transaction(native=>{native.prepare("UPDATE credential_reviews SET status='resolved',decision=?,decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?").run(`${decision}: ${reason}`,profile.email,id);native.prepare("UPDATE certificates SET status=?,revoked_at=CASE WHEN ?='revoke' THEN CURRENT_TIMESTAMP ELSE NULL END,revocation_reason=? WHERE certificate_code=?").run(decision==="restore"?"active":"revoked",decision,decision==="revoke"?reason:null,review.certificate_code);});}
  else return bad("Unknown delivery action.");
  if(!["workspace","recovery","preferences","read-notifications"].includes(action))await recordAudit(profile.email,`delivery.${action}`,{courseCode:code,id:p.id??null});
  return Response.json(result);
}
