import assert from "node:assert/strict";
import test from "node:test";
import { normalizePlan,type RawPlan } from "../src/lib/course-ai";
import { mergeAiDraft,type StudioAiSnapshot } from "../src/lib/ai-draft-merge";
import { defaultCourseDesign,evaluateCourseQuality } from "../src/lib/course-design";
import { gradeInteractive,interactiveIssues,learnerInteractive,type InteractiveActivity } from "../src/lib/interactive-activities";
import { ensureStructuredLearningActivities } from "../src/lib/structured-learning-activities";
const plan:RawPlan={title:"Responsible procurement decisions",discipline:"Business",description:"A practical course for procurement officers to examine evidence and make responsible procurement decisions.",intendedAudience:"Ghanaian procurement officers",prerequisites:"Basic procurement experience",accessibilityStatement:"Readable text and keyboard controls",category:"professional",deliveryPattern:"asynchronous",level:"applied",language:"English",expectedHours:8,objectives:["Evaluate evidence","Apply procurement principles"],skills:["Evidence appraisal"],outcomes:[{statement:"Evaluate procurement evidence.",skill:"Appraisal",assessmentMethod:"Case analysis"},{statement:"Apply procurement rules.",skill:"Application",assessmentMethod:"Quiz"}],sections:[{title:"Evidence",description:"Review evidence",lessonHtml:"<h2>Evidence</h2><p>Verify the source before deciding.</p>",estimatedMinutes:10,activityTitle:"Evidence check",activityInstructions:"Complete this check",videoSearchQuery:"procurement evidence",openResourceQuery:"procurement evidence",outcomeIndexes:[1,999,-1],alignmentReason:"The lesson demonstrates how procurement rules guide evidence verification.",sourceExcerpt:"Verify the source before deciding."},{title:"Rules",description:"Apply the rules",lessonHtml:"<p>Apply the published criteria.</p>",estimatedMinutes:10,activityTitle:"Rule check",activityInstructions:"Compare decisions",videoSearchQuery:"rules",openResourceQuery:"rules"}],assessmentQuestions:[{type:"Multiple choice",prompt:"Which action comes first?",options:["Verify evidence","Guess","Copy","Ignore"],correctAnswer:"Invalid answer",points:1,scheme:"One mark for correct response",feedbackCorrect:"Check reliable evidence",feedbackIncorrect:"Review evidence",learnerAdvice:"Verify the source",outcomeIndexes:[-1,42]}],warnings:[]};
const proposal=()=>normalizePlan({plan:structuredClone(plan),provider:"openai",model:"test",usage:{inputTokens:10,outputTokens:20}},{mode:"idea",provider:"openai",sourceText:"Verify the source before deciding.",sectionCount:2});
test("Invalid AI answer and unsupported outcome links remain unresolved for facilitator correction",()=>{const p=proposal();assert.equal(p.draft.assessmentConfig.questions[0].correctAnswer,"");assert.deepEqual(p.draft.assessmentConfig.questions[0].outcomeIds,[]);assert.deepEqual(p.draft.materials[0].outcomeIds,["ai-outcome-2"]);assert.deepEqual(p.draft.materials[2].outcomeIds,[]);assert.equal(p.draft.materials[0].alignmentConfirmed,false);assert.ok(p.warnings.some(w=>w.includes("did not match")));});
test("Source support is shown only for an exact verified excerpt",()=>{const p=proposal();assert.equal(p.draft.materials[0].sourceExcerpt,"Verify the source before deciding.");const raw=structuredClone(plan);raw.sections[0].sourceExcerpt="Invented source claim";const result=normalizePlan({plan:raw,provider:"openai",model:"test",usage:{inputTokens:0,outputTokens:0}},{mode:"idea",provider:"openai",sourceText:"Real source",sectionCount:2});assert.equal(result.draft.materials[0].sourceExcerpt,undefined);});
test("Outline and unconfirmed AI content prevent publication",()=>{const p=normalizePlan({plan:structuredClone(plan),provider:"openai",model:"test",usage:{inputTokens:0,outputTokens:0}},{mode:"idea",stage:"outline",provider:"openai",sourceText:"Real source",sectionCount:2});assert.ok(p.draft.materials.every(m=>m.developmentPending));const q=evaluateCourseQuality({title:p.draft.title,description:p.draft.description,design:p.draft.design,materials:p.draft.materials,questionCount:1});assert.equal(q.checks.find(c=>c.id==="ai-review")?.passed,false);});
test("Selective AI improvement preserves course fees, governance, certificate, identity and previous approvals",()=>{const d=defaultCourseDesign();d.priceGhs=200;d.certificateFeeGhs=80;d.originatingUnit="CoDE";const current:StudioAiSnapshot={title:"Current title",code:"UCC-EXISTING",description:"Current description",discipline:"Education",design:d,materials:[{id:"existing",title:"Original",kind:"Read",source:"Author",sectionId:d.sections[0].id,outcomeIds:[d.outcomes[0].id]}],activities:[{id:"original-activity",kind:"inline",title:"Original",instructions:"Do the work",materialId:"existing",required:true,passMark:70,attemptsAllowed:4}],assessmentModes:["Human final"],assessmentConfig:{passMark:80,attempts:"5",questionFiles:[{key:"original"}],questions:[{id:"approved-original",approved:true,previewed:true}]},gateRequired:false,questionLimit:10,certificateEnabled:false};const before=structuredClone(current);const result=mergeAiDraft(current,proposal().draft,{overview:false,materials:true,activities:true,questions:true});assert.deepEqual(current,before);assert.equal(result.code,current.code);assert.equal(result.title,current.title);assert.equal(result.design.priceGhs,200);assert.equal(result.design.certificateFeeGhs,80);assert.deepEqual(result.design.certificate,current.design.certificate);assert.equal(result.design.originatingUnit,"CoDE");assert.deepEqual(result.activities[0],current.activities[0]);assert.deepEqual(result.assessmentConfig.questions[0],current.assessmentConfig.questions[0]);assert.equal(result.assessmentConfig.questions[1].approved,false);assert.equal(result.assessmentConfig.passMark,80);assert.equal(result.assessmentConfig.attempts,"5");assert.deepEqual(result.assessmentConfig.questionFiles,current.assessmentConfig.questionFiles);assert.equal(result.gateRequired,false);assert.equal(result.certificateEnabled,false);assert.ok(result.materials.slice(1).every(m=>result.design.sections.some(s=>s.id===m.sectionId)));});
const quiz:InteractiveActivity={kind:"knowledge_check",items:[{id:"a",prompt:"What supports decisions?",choices:["Evidence","Guesswork"],answer:"Evidence",explanation:"Use verifiable evidence."},{id:"b",prompt:"What is the next step?",choices:["Review","Ignore"],answer:"Review",explanation:"Review the relevant criteria."}]};
test("Knowledge checks and decision scenarios grade against retained keys, ignoring client mark fields",()=>{for(const kind of ["knowledge_check","scenario"] as const){const a={...quiz,kind};assert.deepEqual(interactiveIssues(a),[]);const grade=gradeInteractive(a,{selections:{a:"Evidence",b:"Ignore"},mark:100,passed:true},100);assert.equal(grade.mark,50);assert.ok(grade.feedback);const safe=learnerInteractive(a);assert.ok(safe.items.every(i=>!i.answer&&!i.explanation));assert.equal(safe.order,undefined);}});
test("Matching, sequencing and flashcards use explicit server completion evidence",()=>{const pairs:InteractiveActivity={kind:"matching",items:quiz.items.map(i=>({...i,choices:[]}))};assert.equal(gradeInteractive(pairs,{selections:{a:"Evidence",b:"Review"}},100).mark,100);assert.deepEqual(learnerInteractive(pairs).items[0].choices,["Evidence","Review"]);const sequence:InteractiveActivity={kind:"sequencing",items:quiz.items,order:["b","a"]};assert.equal(gradeInteractive(sequence,{order:["b","a"]},100).mark,100);assert.equal(gradeInteractive(sequence,{order:["b","b"]},100).mark,0);assert.equal(learnerInteractive(sequence).order,undefined);const cards:InteractiveActivity={kind:"flashcards",items:quiz.items};assert.equal(gradeInteractive(cards,{reviewed:["a","a"]},100).mark,50);assert.equal(gradeInteractive(cards,{reviewed:["a","b"]},100).mark,100);assert.equal(learnerInteractive(cards).items[0].answer,"Evidence");});
test("Invalid interactive keys block publication and cannot consume a learner attempt",()=>{const invalid={...quiz,items:quiz.items.map(i=>({...i,answer:"Not an option"}))};assert.ok(interactiveIssues(invalid).length);assert.throws(()=>gradeInteractive(invalid,{selections:{}},100));const activity=ensureStructuredLearningActivities([],[{id:"a",kind:"inline",interactive:quiz,gradingMode:"ai_auto",required:false}])[0];assert.equal(activity.gradingMode,"rule");assert.deepEqual(activity.interactive,quiz);});

test("Learner sequencing data does not expose the correct authoring array order",()=>{
  const activity:InteractiveActivity={kind:"sequencing",items:[{id:"x",prompt:"Verify evidence",choices:[]},{id:"y",prompt:"Apply criteria",choices:[]}],order:["x","y"]};
  const redacted=learnerInteractive(activity);
  assert.deepEqual(redacted.items.map(i=>i.id),["y","x"]);
  assert.equal(redacted.order,undefined);
  assert.deepEqual(activity.items.map(i=>i.id),["x","y"]);
  assert.equal(gradeInteractive(activity,{order:["x","y"]},100).mark,100);
});
