import { getRawDb } from "@/db/raw";
import { requireActiveProfile } from "@/lib/accounts";
import { recordAudit } from "@/lib/audit";
import { evaluateCourseQuality, normalizeCourseDesign, type CourseMaterialRecord } from "@/lib/course-design";
import { sanitizeReadableHtml } from "@/lib/document-content";
import { rejectCrossSiteMutation } from "@/lib/request-security";
import type { AssessmentConfigRecord } from "@/lib/assessment-policy";
const parse=<T,>(value:string,fallback:T)=>{try{return JSON.parse(value||"") as T;}catch{return fallback;}};
const safeUrl=(value:unknown)=>{try{const url=new URL(String(value??""));return ["http:","https:"].includes(url.protocol)?url.toString().slice(0,3000):undefined;}catch{return undefined;}};
const snapshotFromRow=(row:Record<string,unknown>)=>({code:row.code,title:row.title,discipline:row.discipline,description:row.description,materials:parse(String(row.materials_json??"[]"),[]),activities:parse(String(row.activities_json??"[]"),[]),assessmentModes:parse(String(row.assessment_modes_json??"[]"),[]),assessmentConfig:parse(String(row.assessment_config_json??"{}"),{}),design:normalizeCourseDesign(parse(String(row.design_json??"{}"),{})),gateRequired:Boolean(row.gate_required),questionLimit:Number(row.question_limit)||10,certificateEnabled:Boolean(row.certificate_enabled)});
const cleanSnapshot=(p:Record<string,unknown>,officialCode:string)=>{const design=normalizeCourseDesign(p.design),materials=(Array.isArray(p.materials)?p.materials:[]).slice(0,250).map((v,index)=>{const m=v as CourseMaterialRecord;return{...m,id:String(m.id??`material-${index+1}`).slice(0,80),title:String(m.title??"").slice(0,240),readableHtml:m.readableHtml?sanitizeReadableHtml(m.readableHtml):undefined,plainText:String(m.plainText??"").slice(0,300000),displayMode:(m.displayMode==="new_tab"?"new_tab":"in_frame") as CourseMaterialRecord["displayMode"],linkedVideoUrl:safeUrl(m.linkedVideoUrl),linkedVideoDisplay:(m.linkedVideoDisplay==="new_tab"?"new_tab":"in_frame") as CourseMaterialRecord["linkedVideoDisplay"],required:m.required!==false};}),activities=(Array.isArray(p.activities)?p.activities:[]).slice(0,100),assessmentConfig=(p.assessmentConfig&&typeof p.assessmentConfig==="object"?p.assessmentConfig:{}) as AssessmentConfigRecord,questionLimit=Math.min(100,Math.max(1,Number(p.questionLimit)||10)),title=String(p.title??"").trim().slice(0,240),description=String(p.description??"").trim().slice(0,5000);const quality=evaluateCourseQuality({title,description,design,materials,questionCount:(assessmentConfig.questions??[]).slice(0,questionLimit).length,assessmentConfig,activities:activities as Parameters<typeof evaluateCourseQuality>[0]["activities"]});return{code:officialCode,title,discipline:String(p.discipline??"Interdisciplinary").trim().slice(0,160),description,design,materials,activities,assessmentModes:Array.isArray(p.assessmentModes)?p.assessmentModes.map(String).slice(0,20):[],assessmentConfig,gateRequired:p.gateRequired!==false,questionLimit,certificateEnabled:p.certificateEnabled!==false,quality};};
export async function GET(){const account=await requireActiveProfile(["facilitator","admin"]);if(account.error||!account.profile)return account.error;const rows=account.profile.role==="admin"?await getRawDb().prepare("SELECT r.*,c.code,c.title live_title,c.certificate_preapproved current_certificate_preapproved,u.full_name facilitator_name FROM course_revisions r JOIN course_drafts c ON c.id=r.course_id LEFT JOIN users u ON u.email=r.created_by_email ORDER BY r.updated_at DESC LIMIT 250").all<Record<string,unknown>>():await getRawDb().prepare("SELECT r.*,c.code,c.title live_title,c.certificate_preapproved current_certificate_preapproved,u.full_name facilitator_name FROM course_revisions r JOIN course_drafts c ON c.id=r.course_id LEFT JOIN users u ON u.email=r.created_by_email WHERE r.created_by_email=? ORDER BY r.updated_at DESC LIMIT 150").bind(account.profile.email).all<Record<string,unknown>>();return Response.json({revisions:rows.results.map(r=>({id:r.id,courseId:r.course_id,revisionNumber:r.revision_number,status:r.status,createdByEmail:r.created_by_email,facilitatorName:r.facilitator_name,reviewComment:r.review_comment,approvalAuthority:r.approval_authority,approvalMeetingDate:r.approval_meeting_date,approvalReference:r.approval_reference,approvalRecordedByEmail:r.approval_recorded_by_email,approvalRecordedAt:r.approval_recorded_at,currentCertificatePreapproved:Boolean(r.current_certificate_preapproved),updatedAt:r.updated_at,...parse(String(r.snapshot_json??"{}"),{})}))});}
export async function POST(request:Request){const origin=rejectCrossSiteMutation(request);if(origin)return origin;const account=await requireActiveProfile(["facilitator","admin"]);if(account.error||!account.profile)return account.error;const p=await request.json() as{courseId?:number};const db=getRawDb(),course=await db.prepare("SELECT * FROM course_drafts WHERE id=? AND status='active'").bind(Number(p.courseId)).first<Record<string,unknown>>();if(!course)return Response.json({error:"Active course not found."},{status:404});if(account.profile.role!=="admin"&&course.created_by_email!==account.profile.email)return Response.json({error:"You may revise only your own active courses."},{status:403});const open=await db.prepare("SELECT * FROM course_revisions WHERE course_id=? AND created_by_email=? AND status IN ('draft','rejected','pending_review') ORDER BY revision_number DESC LIMIT 1").bind(p.courseId,account.profile.email).first<Record<string,unknown>>();if(open)return Response.json({revision:{id:open.id,courseId:open.course_id,revisionNumber:open.revision_number,status:open.status,...parse(String(open.snapshot_json),{})}});const latest=await db.prepare("SELECT MAX(revision_number) maximum FROM course_revisions WHERE course_id=?").bind(p.courseId).first<{maximum:number|null}>(),number=Number(latest?.maximum??0)+1,snapshot=snapshotFromRow(course);const saved=await db.prepare("INSERT INTO course_revisions(course_id,revision_number,snapshot_json,status,created_by_email) VALUES(?,?,?,'draft',?)").bind(p.courseId,number,JSON.stringify(snapshot),account.profile.email).run();await recordAudit(account.profile.email,"course.revision_created",{courseId:p.courseId,revisionNumber:number});return Response.json({revision:{id:saved.meta.last_row_id,courseId:p.courseId,revisionNumber:number,status:"draft",...snapshot}},{status:201});}
export async function PUT(request:Request){const origin=rejectCrossSiteMutation(request);if(origin)return origin;const account=await requireActiveProfile(["facilitator","admin"]);if(account.error||!account.profile)return account.error;const p=await request.json() as Record<string,unknown>,id=Number(p.revisionId),db=getRawDb(),row=await db.prepare("SELECT r.*,c.code FROM course_revisions r JOIN course_drafts c ON c.id=r.course_id WHERE r.id=?").bind(id).first<Record<string,unknown>>();if(!row)return Response.json({error:"Revision not found."},{status:404});if(account.profile.role!=="admin"&&row.created_by_email!==account.profile.email)return Response.json({error:"You may edit only your own revision."},{status:403});if(!["draft","rejected"].includes(String(row.status)))return Response.json({error:"This revision is locked while under review or after application."},{status:409});const snapshot=cleanSnapshot(p,String(row.code)),submit=p.submissionMode==="review";if(submit&&!snapshot.quality.ready)return Response.json({error:"Complete every publish-readiness check before review.",quality:snapshot.quality},{status:400});const{quality,...stored}=snapshot,status=submit?"pending_review":"draft";await db.prepare("UPDATE course_revisions SET snapshot_json=?,status=?,review_comment=NULL,submitted_at=CASE WHEN ?='pending_review' THEN CURRENT_TIMESTAMP ELSE submitted_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(stored),status,status,id).run();await recordAudit(account.profile.email,submit?"course.revision_submitted":"course.revision_saved",{revisionId:id,courseId:row.course_id});return Response.json({revision:{id,courseId:row.course_id,revisionNumber:row.revision_number,status,...stored},quality});}
export async function PATCH(request:Request){
  const origin=rejectCrossSiteMutation(request);if(origin)return origin;
  const account=await requireActiveProfile(["admin"]);if(account.error||!account.profile)return account.error;
  const p=await request.json() as{revisionId?:number;status?:"applied"|"rejected";comment?:string;approvalAuthority?:string;approvalMeetingDate?:string;approvalReference?:string;certificatePreapproved?:boolean};
  const comment=String(p.comment??"").trim().slice(0,4000);
  if(!p.revisionId||!["applied","rejected"].includes(p.status??""))return Response.json({error:"Choose a valid revision decision."},{status:400});
  if(p.status==="rejected"&&!comment)return Response.json({error:"Add comments explaining required corrections."},{status:400});
  if(p.status==="applied"&&(!String(p.approvalAuthority??"").trim()||!String(p.approvalMeetingDate??"").trim()||!String(p.approvalReference??"").trim()))return Response.json({error:"Record the approving committee/authority, meeting date and minute/reference number before applying the amendment."},{status:400});
  const db=getRawDb();
  const row=await db.prepare("SELECT r.*,c.code,c.certificate_preapproved,c.created_by_email AS course_creator_email FROM course_revisions r JOIN course_drafts c ON c.id=r.course_id WHERE r.id=? AND r.status='pending_review'").bind(p.revisionId).first<Record<string,unknown>>();
  if(!row)return Response.json({error:"Pending revision not found."},{status:404});
  const snapshot=parse<Record<string,unknown>>(String(row.snapshot_json),{}),clean=cleanSnapshot(snapshot,String(row.code));
  if(p.status==="applied"&&!clean.quality.ready)return Response.json({error:"Application is blocked until every readiness check passes.",quality:clean.quality},{status:409});
  const existingCertificatePreapproval=Boolean(row.certificate_preapproved);
  if(p.status==="applied"&&clean.certificateEnabled&&!existingCertificatePreapproval&&!p.certificatePreapproved)return Response.json({error:"Confirm programme-level certificate pre-authorisation before applying an amendment that enables certification."},{status:409});
  if(p.status==="applied"){
    const nextCertificatePreapproval=clean.certificateEnabled&&(existingCertificatePreapproval||Boolean(p.certificatePreapproved))?1:0;
    await db.prepare(`UPDATE course_drafts SET title=?,discipline=?,description=?,materials_json=?,activities_json=?,assessment_modes_json=?,assessment_config_json=?,design_json=?,gate_required=?,question_limit=?,certificate_enabled=?,certificate_preapproved=?,version_number=version_number+1,activated_by_email=?,activated_at=CURRENT_TIMESTAMP,review_comment=?,reviewed_by_email=?,reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='active'`)
      .bind(clean.title,clean.discipline,clean.description,JSON.stringify(clean.materials),JSON.stringify(clean.activities),JSON.stringify(clean.assessmentModes),JSON.stringify(clean.assessmentConfig),JSON.stringify(clean.design),clean.gateRequired?1:0,clean.questionLimit,clean.certificateEnabled?1:0,nextCertificatePreapproval,account.profile.email,comment||"Approved amendment record applied.",account.profile.email,row.course_id).run();
    const colabActivities=(clean.activities as {kind?:string;title?:string;instructions?:string;notebookKey?:string;notebookFileName?:string;templateUrl?:string;rubric?:string;maxMark?:number;passMark?:number;attemptsAllowed?:number;dueAt?:string;sectionId?:string;gradingMode?:string}[]).filter((activity)=>activity.kind==="colab"&&activity.notebookKey&&activity.notebookFileName);
    for(const activity of colabActivities){
      const title=activity.title?.trim()||"Colab coding activity";
      const gradingMode=["facilitator","ai_auto","ai_luna","ai_terra"].includes(String(activity.gradingMode))?String(activity.gradingMode):"ai_auto";
      const existing=await db.prepare("SELECT id FROM colab_assignments WHERE course_code=? AND title=? LIMIT 1").bind(String(row.code),title).first<{id:number}>();
      const values=[activity.instructions||"Complete the notebook in free Google Colab and submit your evidence.",activity.notebookKey,activity.notebookFileName,activity.templateUrl||null,activity.rubric||"Assess correctness, interpretation and reproducibility.",Math.min(1000,Math.max(1,Number(activity.maxMark)||100)),Math.min(100,Math.max(1,Number(activity.passMark)||60)),Math.min(10,Math.max(1,Number(activity.attemptsAllowed)||2)),activity.dueAt||null,activity.sectionId||null,gradingMode] as const;
      if(existing) await db.prepare("UPDATE colab_assignments SET instructions=?,template_file_key=?,template_file_name=?,template_url=?,rubric=?,max_mark=?,pass_mark=?,attempts_allowed=?,due_at=?,section_id=?,grading_mode=?,status='active' WHERE id=?").bind(...values,existing.id).run();
      else await db.prepare("INSERT INTO colab_assignments(course_code,title,instructions,template_file_key,template_file_name,template_url,rubric,max_mark,pass_mark,attempts_allowed,due_at,section_id,grading_mode,status,created_by_email) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'active',?)").bind(String(row.code),title,...values,String(row.course_creator_email||row.created_by_email)).run();
    }
  }
  await db.prepare("UPDATE course_revisions SET status=?,review_comment=?,reviewed_by_email=?,reviewed_at=CURRENT_TIMESTAMP,applied_at=CASE WHEN ?='applied' THEN CURRENT_TIMESTAMP ELSE NULL END,approval_authority=CASE WHEN ?='applied' THEN ? ELSE approval_authority END,approval_meeting_date=CASE WHEN ?='applied' THEN ? ELSE approval_meeting_date END,approval_reference=CASE WHEN ?='applied' THEN ? ELSE approval_reference END,approval_recorded_by_email=CASE WHEN ?='applied' THEN ? ELSE approval_recorded_by_email END,approval_recorded_at=CASE WHEN ?='applied' THEN CURRENT_TIMESTAMP ELSE approval_recorded_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?")
    .bind(p.status,comment||"Approved amendment record applied.",account.profile.email,p.status,p.status,String(p.approvalAuthority??"").trim().slice(0,300),p.status,String(p.approvalMeetingDate??"").trim().slice(0,40),p.status,String(p.approvalReference??"").trim().slice(0,240),p.status,account.profile.email,p.status,p.revisionId).run();
  await recordAudit(account.profile.email,p.status==="applied"?"course.revision_applied_from_committee_record":"course.revision_rejected",{revisionId:p.revisionId,courseId:row.course_id,comment,approvalReference:p.approvalReference??null,approvalAuthority:p.approvalAuthority??null,certificatePreapproved:clean.certificateEnabled?(existingCertificatePreapproval||Boolean(p.certificatePreapproved)):false});
  return Response.json({updated:true,status:p.status});
}
