"use client";

import { useState } from "react";
import { GraduationCap, ShieldCheck } from "lucide-react";

export default function AuthForm({ returnTo }: { returnTo: string }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch("/api/render-auth", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, fullName, email, password, returnTo }) }); const result = await response.json() as { error?: string; returnTo?: string }; if (!response.ok) throw new Error(result.error ?? "Authentication failed."); window.location.assign(result.returnTo ?? "/"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Authentication failed."); } finally { setLoading(false); } };
  return <main className="access-shell render-auth-shell"><section className="access-card render-auth-card"><div className="access-brand"><div className="brand-mark"><GraduationCap size={28} /></div><div><strong>UCC Microcredentials</strong><span>University of Cape Coast</span></div></div><p className="eyebrow">SECURE PLATFORM ACCESS</p><h1>{mode === "login" ? "Sign in to your portal." : "Create your learner account."}</h1><p>{mode === "login" ? "Facilitators use the email invited by the administrator. Learners use the account they created here." : "After account creation, complete your biodata, national ID and live-selfie verification."}</p><div className="auth-mode"><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Sign in</button><button className={mode === "register" ? "active" : ""} onClick={() => setMode("register")}>New learner</button></div><form className="render-auth-form" onSubmit={submit}>{mode === "register" && <label>Full legal name<input value={fullName} onChange={(event) => setFullName(event.target.value)} autoComplete="name" required /></label>}<label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /></label><label>Password<input type="password" minLength={10} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={mode === "login" ? "current-password" : "new-password"} required /><span>Minimum 10 characters</span></label>{error && <div className="auth-error">{error}</div>}<button className="access-primary" disabled={loading}><ShieldCheck size={18} /> {loading ? "Please wait…" : mode === "login" ? "Sign in securely" : "Create learner account"}</button></form><small>Passwords are salted and hashed. Identity evidence remains restricted to authorised reviewers.</small></section></main>;
}
