"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
export function AiAuthoringAdministration() {
  const [limit, setLimit] = useState(30), [draft, setDraft] = useState<number | null>(null), [usage, setUsage] = useState<{owner_email:string;requests:number;input_tokens:number;output_tokens:number}[]>([]), [ready, setReady] = useState(false);
  useEffect(() => { let cancelled = false; const load = async () => { try { const r = await fetch("/api/course-ai/jobs"); if (!r.ok) return; const d = await r.json(); if (!cancelled && d.admin) { setReady(true); setLimit(d.dailyLimit); setUsage(d.institutionUsage || []); } } catch {} }; void load(); const timer = setInterval(() => void load(), 15000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  if (!ready) return null;
  return <details className="studio-tools ai-authoring-administration"><summary>AI authoring usage and limits</summary><p>Daily limits reserve one provider call per outline, diagnostic or lesson section. Resuming a failed staged course reserves only its unfinished sections.</p><table><thead><tr><th>Facilitator</th><th>Calls reserved</th><th>Input tokens</th><th>Output tokens</th></tr></thead><tbody>{usage.map(u=><tr key={u.owner_email}><td>{u.owner_email}</td><td>{u.requests}</td><td>{u.input_tokens||0}</td><td>{u.output_tokens||0}</td></tr>)}</tbody></table><form onSubmit={async e=>{e.preventDefault();const r=await fetch("/api/course-ai/jobs",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dailyLimit:draft??limit})}),d=await r.json();if(!r.ok)return toast.error(d.error);setLimit(d.dailyLimit);setDraft(null);toast.success("AI authoring limit saved");}}><label>Daily provider calls per facilitator<input type="number" min={1} max={500} value={draft??limit} onChange={e=>setDraft(Number(e.target.value))}/></label><button type="submit">Save AI usage limit</button></form><p>Token usage is reported by the provider when available. OCR extraction and external tool charges are separate.</p></details>;
}
