"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { BookOpen, CalendarDays, CheckCircle2, Download, MessageSquareText, RefreshCw, Save } from "lucide-react";
import type { CourseDesign } from "@/lib/course-design";
import { normalizeDeliveryPolicy, assessmentRequired } from "@/lib/delivery-policy";

type Row=Record<string,unknown>;
const s=(v:unknown)=>String(v??"");
const rows=(v:unknown):Row[]=>Array.isArray(v)?v.filter((r):r is Row=>Boolean(r&&typeof r==="object")):[];
const when=(v:unknown)=>v?new Date(s(v).includes("T")?s(v):`${s(v).replace(" ","T")}Z`).toLocaleString():"Not recorded";
async function jsonRequest(url:string,body?:Row,method="POST") {const response=await fetch(url,body?{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const result=await response.json() as Row;if(!response.ok)throw new Error(s(result.error)||"This request could not be completed.");return result;}
export async function saveWorkspace(code:string,key:string,value:unknown) {return jsonRequest("/api/delivery",{action:"workspace",courseCode:code,key,value});}
function exportCsv(name:string,items:Row[],columns:string[]) {
  const safe=(v:unknown)=>{let value=s(v);if(/^[=+\-@\t\r]/.test(value))value=`'${value}`;return `"${value.replaceAll('"','""')}"`;};
  const blob=new Blob(["\ufeff"+[columns.join(","),...items.map(row=>columns.map(c=>safe(row[c])).join(","))].join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);
}
type Field={key:string;label:string;type?:string;options?:string[];required?:boolean};
function ActionForm({action,courseCode,fields,onSaved,initial={},label="Save"}:{action:string;courseCode?:string;fields:Field[];onSaved:()=>void;initial?:Row;label?:string}) {
  const [value,setValue]=useState<Row>(initial),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <form className="delivery-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await jsonRequest("/api/delivery",{...value,...Object.fromEntries(fields.filter(f=>f.type==="datetime-local"&&value[f.key]).map(f=>[f.key,new Date(s(value[f.key])).toISOString()])),action,courseCode});setValue(initial);onSaved();toast.success("Saved");}catch(err){setError(err instanceof Error?err.message:"Save failed.");}finally{setBusy(false);}}}>{fields.map(f=><label key={f.key}>{f.label}{f.options?<select value={s(value[f.key])} onChange={e=>setValue({...value,[f.key]:e.target.value})} required={f.required!==false}><option value="">Choose</option>{f.options.map(v=><option key={v}>{v}</option>)}</select>:f.type==="textarea"?<textarea value={s(value[f.key])} onChange={e=>setValue({...value,[f.key]:e.target.value})} required={f.required!==false} />:<input type={f.type||"text"} value={s(value[f.key])} onChange={e=>setValue({...value,[f.key]:e.target.value})} required={f.required!==false} />}</label>)}<button className="secondary-action" disabled={busy}>{busy?"Saving…":label}</button>{error&&<p className="delivery-error" role="alert">{error}</p>}</form>;
}
function RecordTable({items,columns}:{items:Row[];columns:{key:string;label:string;render?:(row:Row)=>React.ReactNode}[]}) {return <div className="delivery-table-scroll" tabIndex={0} aria-label="Scrollable records"><table className="delivery-table"><thead><tr>{columns.map(c=><th scope="col" key={c.key}>{c.label}</th>)}</tr></thead><tbody>{items.map((row,i)=><tr key={s(row.id||row.user_email||row.reference)||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):s(row[c.key])||"—"}</td>)}</tr>)}</tbody></table>{!items.length&&<p className="delivery-empty">No records yet.</p>}</div>;}

export function DeliveryWorkspace({area,role="learner",initialCourse="",compact=false}:{area:string;role?:string;initialCourse?:string;compact?:boolean}) {
  const [code,setCode]=useState(initialCourse),[data,setData]=useState<Row>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[filter,setFilter]=useState(""),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[replyTo,setReplyTo]=useState<Row|null>(null),requestSequence=useRef(0);
  const load=useCallback(async()=>{const sequence=++requestSequence.current;setLoading(true);try{const result=await jsonRequest(`/api/delivery?area=${encodeURIComponent(area)}&courseCode=${encodeURIComponent(code)}&month=${month}`);if(sequence!==requestSequence.current)return;setData(result);setError("");}catch(e){if(sequence!==requestSequence.current)return;setError(e instanceof Error?e.message:"Could not load records.");}finally{if(sequence===requestSequence.current)setLoading(false);}},[area,code,month]);
  useEffect(()=>{void load();},[load]);
  const mutate=async(body:Row)=>{try{await jsonRequest("/api/delivery",{courseCode:code,...body});await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not save.");}};
  const courses=rows(data.courses),items=rows(data.items),staff=role!=="learner",title:Record<string,string>={overview:staff?"Teaching priorities":"Your saved learning",assessments:"Assessments and feedback",posts:"Course community",sessions:"Live sessions and recordings",gradebook:"Gradebook and engagement",teams:"Course teams",cohorts:"Intakes and cohorts",payments:"Payments and refund requests",notifications:"Notifications",preferences:"Reminder preferences",usage:"Anovlad usage reconciliation","credential-reviews":"Certificate decision reviews"};
  const permissions=(data.permissions||{}) as Row;
  const courseAreas=["posts","sessions","teams","cohorts","gradebook"];
  const filtered=items.filter(row=>JSON.stringify(row).toLowerCase().includes(filter.toLowerCase()));
  return <section className={`page-panel delivery-workspace ${compact?"compact":""}`}><div className="page-title"><div><p className="eyebrow">UCC GROWTH+</p><h2>{title[area]||"Course delivery"}</h2></div><button className="secondary-action" onClick={()=>void load()} aria-label="Refresh records"><RefreshCw size={17}/></button></div>{courseAreas.includes(area)&&<label className="delivery-course-picker">Course<select value={code} onChange={e=>{setData({courses});setCode(e.target.value);}}><option value="">{area==="sessions"?"All my courses":"Choose a course"}</option>{courses.map(c=><option key={s(c.code)} value={s(c.code)}>{s(c.code)} · {s(c.title)}</option>)}</select></label>}{error&&<p role="alert" className="delivery-error">{error}</p>}{loading&&<p role="status">Loading records…</p>}
    {area==="overview"&&<div className="delivery-card-grid">{staff?rows(data.queues).map(q=><article key={s(q.code)}><b>{s(q.title)}</b><p>{s(q.pending)} awaiting marking · {s(q.overdue)} overdue feedback</p><p>{s(q.at_risk)} learners without engagement in 14 days · {s(q.unanswered)} unanswered discussions</p><a href={`/?view=delivery&courseCode=${encodeURIComponent(s(q.code))}`}>Open delivery workspace</a></article>):rows(data.records).map(r=><article key={s(r.courseCode)}><b>{s(r.title)}</b><progress max={100} value={Number(r.progress)||0} aria-label={`${s(r.title)} learning progress`}/><p>{s(r.progress)}% learning complete</p><a href={s(r.resumeUrl)}><BookOpen size={16}/> Resume saved lesson</a>{r.assessmentDueAt?<small>Assessment due {when(r.assessmentDueAt)}</small>:null}</article>)}</div>}
    {area==="assessments"&&rows(data.records).map(record=><article className="delivery-record" key={s(record.courseCode)}><header><h3>{s(record.title)}</h3><a href={`/learn/${encodeURIComponent(s(record.courseCode))}`}>Open course assessment</a></header><p>{record.assessmentDueAt?`Due ${when(record.assessmentDueAt)}`:"Self-paced assessment"} · Feedback target {s(record.feedbackDays)} days · {s(record.markingMode)} marking</p>{rows(record.attempts).map(attempt=><details key={s(attempt.id)}><summary>Attempt {s(attempt.attempt_number)} · {s(attempt.status).replaceAll("_"," ")} · {attempt.final_score==null?"Result pending":`${s(attempt.final_score)}%`}</summary><p>Receipt UGP-AS-{s(attempt.id)} · Submitted {when(attempt.submitted_at)}</p><p>{s(attempt.marker_feedback)||"Automatic question feedback is available in the full attempt record below."}</p><AttemptDetail id={Number(attempt.id)}/>{["marked","resubmit"].includes(s(attempt.status))&&<ActionForm action="appeal" initial={{submissionId:attempt.id}} fields={[{key:"reason",label:"Explain an appeal",type:"textarea"}]} onSaved={()=>void load()} label="Submit appeal"/>}</details>)}{!rows(record.attempts).length&&<p>No submission yet.</p>}</article>)}
    {area==="posts"&&code&&<><ActionForm key={`post-${replyTo?.id||"new"}-${code}`} action="post" courseCode={code} initial={replyTo?{parentId:replyTo.id,kind:"discussion",title:`Re: ${s(replyTo.title)}`}:{kind:"discussion"}} fields={[{key:"title",label:replyTo?"Reply title":"Post title"},{key:"message",label:"Message",type:"textarea"},...(staff&&Boolean(permissions.teach)&&!replyTo?[{key:"kind",label:"Post type",options:["discussion","announcement"]}]:[])]} onSaved={()=>{setReplyTo(null);void load();}} label={replyTo?"Send reply":"Publish post"}/>{replyTo&&<button onClick={()=>setReplyTo(null)}>Cancel reply</button>}<div className="delivery-posts">{items.map(post=><article key={s(post.id)}><header><b>{s(post.title)}</b><small>{s(post.kind)} · {s(post.author_name)} · {when(post.created_at)}</small></header>{post.parent_id?<small>Reply to post #{s(post.parent_id)}</small>:null}<p>{s(post.message)}</p><button onClick={()=>setReplyTo(post)}><MessageSquareText size={16}/> Reply</button>{staff&&Boolean(permissions.moderate)&&<button onClick={()=>void mutate({action:"moderate-post",id:post.id,hidden:true})}>Hide post</button>}</article>)}</div></>}
    {area==="sessions"&&<>{staff&&code&&Boolean(permissions.teach)&&<details><summary>Create a live session</summary><ActionForm action="session" courseCode={code} fields={[{key:"title",label:"Session title"},{key:"startsAt",label:"Start (your local time)",type:"datetime-local"},{key:"endsAt",label:"End (your local time)",type:"datetime-local"},{key:"meetingUrl",label:"Meeting URL",type:"url"},{key:"recordingUrl",label:"Recording URL",type:"url",required:false}]} onSaved={()=>void load()} label="Schedule session"/></details>}<div className="delivery-card-grid">{items.map(session=><article key={s(session.id)}><small>{s(session.course_code)}</small><h3>{s(session.title)}</h3><p>{when(session.starts_at)} to {when(session.ends_at)}</p><a href={s(session.meeting_url)} target="_blank" rel="noopener noreferrer">Join meeting</a>{session.recording_url?<a href={s(session.recording_url)} target="_blank" rel="noopener noreferrer">Watch recording</a>:null}<button onClick={()=>downloadSessionCalendar(session)}><CalendarDays size={16}/> Save calendar event</button>{(!staff||!permissions.teach)?<small>Attendance: {Number(session.attended)===1?"Recorded by teaching team":"Not recorded"}</small>:<><details><summary>Attendance and session updates</summary><ActionForm action="attendance" courseCode={s(session.course_code)} initial={{sessionId:session.id,attended:true}} fields={[{key:"email",label:"Enrolled learner email",type:"email"}]} onSaved={()=>void load()} label="Record attendance"/><ActionForm action="session" courseCode={s(session.course_code)} initial={{id:session.id,title:session.title,startsAt:session.starts_at,endsAt:session.ends_at,meetingUrl:session.meeting_url,recordingUrl:session.recording_url}} fields={[{key:"title",label:"Title"},{key:"startsAt",label:"Start (UTC)",type:"text"},{key:"endsAt",label:"End (UTC)",type:"text"},{key:"meetingUrl",label:"Meeting URL",type:"url"},{key:"recordingUrl",label:"Recording URL",type:"url",required:false}]} onSaved={()=>void load()} label="Update session"/></details><button onClick={()=>void mutate({action:"cancel-session",courseCode:session.course_code,id:session.id})}>Cancel session</button></>}</article>)}</div>{!items.length&&!loading&&<p>No sessions are scheduled.</p>}</>}
    {area==="teams"&&code&&<><p>Co-facilitators teach and mark. Markers grade assigned course evidence. Moderators review discussions and appeals. Course owners and administrators assign access.</p>{permissions.manage?<ActionForm action="team" courseCode={code} fields={[{key:"email",label:"Active facilitator email",type:"email"},{key:"role",label:"Course role",options:["cofacilitator","marker","moderator","remove"]}]} onSaved={()=>void load()}/>:<p>Only the course owner or administrator can change this team.</p>}<RecordTable items={rows(data.team)} columns={[{key:"full_name",label:"Name"},{key:"user_email",label:"Email"},{key:"team_role",label:"Role"}]}/></>}
    {area==="cohorts"&&code&&Boolean(permissions.teach)&&<><details><summary>Create a separate course intake</summary><p>A new approved offering code keeps each intake’s enrolments, attempts and credentials separate. The approved curriculum is copied; content amendments still require governance approval.</p><ActionForm action="run" courseCode={code} fields={[{key:"name",label:"Intake name"},{key:"offeringCode",label:"Unique course offering code"},{key:"startsAt",label:"Starts",type:"datetime-local"},{key:"endsAt",label:"Ends",type:"datetime-local"},{key:"enrolmentClosesAt",label:"Enrolment closes",type:"datetime-local"},{key:"capacity",label:"Capacity (0 means no limit)",type:"number",required:false}]} onSaved={()=>void load()} label="Create intake"/></details><RecordTable items={rows(data.runs)} columns={[{key:"name",label:"Intake"},{key:"offering_code",label:"Offering code"},{key:"starts_at",label:"Start"},{key:"ends_at",label:"End"},{key:"capacity",label:"Capacity"}]}/><ActionForm action="cohort" courseCode={code} fields={[{key:"name",label:"New cohort name"}]} onSaved={()=>void load()} label="Create cohort"/><RecordTable items={rows(data.cohorts)} columns={[{key:"id",label:"Cohort ID"},{key:"name",label:"Name"},{key:"members",label:"Members"}]}/><ActionForm action="cohort-member" courseCode={code} fields={[{key:"cohortId",label:"Cohort ID",type:"number"},{key:"email",label:"Enrolled learner email",type:"email"}]} onSaved={()=>void load()} label="Add cohort member"/></>}
    {area==="gradebook"&&code&&Boolean(permissions.mark)&&<EvidenceQueue courseCode={code}/>}
    {(area==="cohorts"||area==="gradebook")&&code&&<><label>Filter learners, cohort or status<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><button className="secondary-action" onClick={()=>exportCsv(`${code}-gradebook.csv`,filtered.map(row=>({...row,progress:(row.record as Row|undefined)?.progress})),["user_email","full_name","status","cohorts","score","passed","progress","last_activity"])}><Download size={16}/> Export filtered records</button><RecordTable items={filtered} columns={[{key:"full_name",label:"Learner"},{key:"user_email",label:"Email"},{key:"cohorts",label:"Cohort"},{key:"status",label:"Enrolment"},{key:"score",label:"Final score"},{key:"last_activity",label:"Last engagement",render:r=>when(r.last_activity)},...(area==="gradebook"?[{key:"record",label:"Assessment and learning records",render:(r:Row)=><GradebookLearner canMark={Boolean(permissions.mark)} record={r.record as Row} courseCode={code} onSaved={()=>void load()}/>}]:[])]}/>{area==="gradebook"&&<><h3>Appeals</h3>{rows(data.appeals).map(appeal=><details key={s(appeal.id)}><summary>{s(appeal.user_email)} · {s(appeal.status)}</summary><p>{s(appeal.reason)}</p><p>{s(appeal.response)}</p>{appeal.status==="open"&&Boolean(permissions.moderate)&&<ActionForm action="appeal-decision" courseCode={code} initial={{id:appeal.id}} fields={[{key:"response",label:"Moderator response",type:"textarea"}]} onSaved={()=>void load()}/>}</details>)}<h3>Course evaluations</h3><RecordTable items={rows(data.evaluations)} columns={[{key:"rating",label:"Rating /5"},{key:"feedback",label:"Feedback"},{key:"updated_at",label:"Date"}]}/></>}</>}
    {area==="notifications"&&<><button onClick={()=>void mutate({action:"read-notifications"})}>Mark all read</button>{items.map(item=><article className={`delivery-record ${item.read_at?"read":"unread"}`} key={s(item.id)}><b>{s(item.title)}</b><p>{s(item.message)}</p><small>{when(item.created_at)}</small><a href={s(item.link)}>Open record</a><button onClick={()=>void mutate({action:"read-notifications",id:item.id})}>Mark read</button>{item.email_status==="failed"&&<button onClick={()=>void mutate({action:"retry-email",id:item.id})}>Retry email</button>}</article>)}{!items.length&&!loading&&<p>You have no notifications.</p>}</>}
    {area==="preferences"&&data.preferences?<Preferences key={JSON.stringify(data.preferences)} value={data.preferences as Row} onSaved={()=>void load()}/>:null}
    {area==="payments"&&<><p>Course and certificate payments are UCC learner fees. Refund requests require a UCC decision and payment-provider processing.</p><RecordTable items={items} columns={[{key:"reference",label:"Reference"},{key:"course_code",label:"Course"},{key:"purpose",label:"Purpose"},{key:"amount_pesewas",label:"Amount",render:r=>`${s(r.currency)} ${(Number(r.amount_pesewas)/100).toFixed(2)}`},{key:"status",label:"Status"},{key:"refund_status",label:"Refund"},{key:"actions",label:"Receipt",render:r=>r.status==="paid"?<a href={`/api/payments/receipt?reference=${encodeURIComponent(s(r.reference))}`}>Download PDF receipt</a>:null}]}/>{!staff&&<ActionForm action="refund-request" fields={[{key:"reference",label:"Paid reference"},{key:"reason",label:"Refund reason",type:"textarea"}]} onSaved={()=>void load()} label="Request refund"/>}{role==="admin"&&rows(data.refunds).map(refund=><details key={s(refund.id)}><summary>{s(refund.payment_reference)} · {s(refund.status)}</summary><p>{s(refund.reason)}</p><ActionForm action="refund-decision" initial={{id:refund.id}} fields={[{key:"status",label:"Decision",options:["approved","rejected","completed"]},{key:"response",label:"UCC response",type:"textarea"},{key:"externalReference",label:"Provider refund reference (required when completed)",required:false}]} onSaved={()=>void load()}/></details>)}</>}
    {area==="usage"&&data.report?<><label>UTC billing month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><UsageReport report={data.report as Row}/><button onClick={()=>exportCsv(`anovlad-usage-${month}.csv`,rows((data.report as Row).users),["email","full_name","courses","last_activity"])}>Export reconciliation CSV</button><ActionForm action="billing-settings" fields={[{key:"definition",label:"Contract billing definition",options:["engaged","enrolled"]},{key:"rateGhs",label:"Agreed GHS per learner",type:"number"}]} onSaved={()=>void load()}/><ActionForm action="test-account" fields={[{key:"email",label:"Learner test account",type:"email"}]} initial={{isTest:true}} onSaved={()=>void load()} label="Exclude test account"/>{data.frozen?<p>Monthly reconciliation has been frozen for review. The stored report preserves its original count and rate.</p>:<button onClick={()=>void mutate({action:"freeze-usage",month})}>Freeze monthly reconciliation</button>}</>:null}
    {area==="credential-reviews"&&items.map(review=><details key={s(review.id)}><summary>{s(review.learner_name)} · {s(review.course_code)} · {s(review.status)}</summary><p>{s(review.reason)}</p>{review.status==="open"&&<ActionForm action="credential-review" initial={{id:review.id}} fields={[{key:"decision",label:"Authorised decision",options:["restore","revoke"]},{key:"reason",label:"Decision reason",type:"textarea"}]} onSaved={()=>void load()}/>}</details>)}
    {data.nextCursor?<button onClick={async()=>{try{const next=await jsonRequest(`/api/delivery?area=${area}&courseCode=${encodeURIComponent(code)}&before=${data.nextCursor}`);setData({...next,items:[...items,...rows(next.items)]});}catch(e){toast.error(e instanceof Error?e.message:"Load failed.");}}}>Load older records</button>:null}{data.nextOffset?<button onClick={async()=>{const next=await jsonRequest(`/api/delivery?area=${area}&courseCode=${encodeURIComponent(code)}&offset=${data.nextOffset}`);setData({...next,items:[...items,...rows(next.items)]});}}>Load more records</button>:null}
  </section>;
}
function Preferences({value,onSaved}:{value:Row;onSaved:()=>void}) {const [form,setForm]=useState(value);return <form className="delivery-preferences" onSubmit={async e=>{e.preventDefault();try{await jsonRequest("/api/delivery",{action:"preferences",...form});onSaved();toast.success("Preferences saved");}catch(err){toast.error(err instanceof Error?err.message:"Could not save.");}}}>{Object.entries({assessment_reminders:"Assessment deadline and result notifications",session_reminders:"Live-session reminders",teaching_alerts:"Teaching queue notifications",weekly_digest:"Weekly learning digest",email_enabled:"Send these notifications by email"}).map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(form[key])} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>)}<p>Notifications stay available in the portal. Optional emails use the configured Google OAuth or other transactional provider.</p><button className="secondary-action"><Save size={16}/> Save preferences</button></form>;}
function UsageReport({report}:{report:Row}) {return <div className="delivery-record"><h3>{s(report.billableUsers)} billable learners · GHS {Number(report.totalGhs).toFixed(2)}</h3><p>{s(report.definitionText)}</p><small>{s(report.excludes)}</small></div>;}
function GradebookLearner({record,courseCode,onSaved,canMark}:{record:Row;courseCode:string;onSaved:()=>void;canMark:boolean}) {return <details><summary>{s(record?.progress)}% learning · {rows(record?.attempts).length} attempts</summary>{rows(record?.requirements).map(r=><p key={s(r.id)}>{r.complete?"✓":"○"} {s(r.label)}</p>)}{rows(record?.attempts).map(attempt=><div key={s(attempt.id)}><p>Attempt {s(attempt.attempt_number)} · {s(attempt.status)} · {s(attempt.final_score)}%</p>{canMark?<MarkAttempt id={Number(attempt.id)} onSaved={onSaved}/>:<AttemptDetail id={Number(attempt.id)}/>}{canMark&&<button onClick={async()=>{try{await jsonRequest("/api/delivery",{action:"retry-grading",courseCode,id:attempt.id});onSaved();}catch(e){toast.error(e instanceof Error?e.message:"Retry failed.");}}}>Retry failed automatic grading</button>}</div>)}</details>;}
function MarkAttempt({id,onSaved}:{id:number;onSaved:()=>void}) {const [score,setScore]=useState(""),[feedback,setFeedback]=useState(""),[busy,setBusy]=useState(false);return <><AttemptDetail id={id}/><form className="delivery-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await jsonRequest("/api/assessments",{id,decision:"marked",finalScore:Number(score),feedback},"PATCH");onSaved();toast.success("Grade decision recorded");}catch(error){toast.error(error instanceof Error?error.message:"Could not mark.");}finally{setBusy(false);}}}><label>Final score /100<input type="number" min={0} max={100} value={score} onChange={e=>setScore(e.target.value)} required/></label><label>Feedback and correction reason<textarea minLength={10} value={feedback} onChange={e=>setFeedback(e.target.value)} required/></label><button disabled={busy}>Record final decision</button></form></>;}
function AttemptDetail({id}:{id:number}) {const [detail,setDetail]=useState<Row|null>(null);return <details onToggle={e=>{if(e.currentTarget.open&&!detail)void Promise.all([jsonRequest(`/api/assessments?id=${id}`),jsonRequest(`/api/delivery?area=assessment-history&id=${id}`)]).then(([submissions,history])=>setDetail({...history,submission:rows(submissions.submissions).find(r=>Number(r.id)===id)})).catch(error=>toast.error(error instanceof Error?error.message:"Could not load attempt."));}}><summary>Answers, rubric feedback and decision history</summary>{detail&&<><section className="delivery-evidence">{Object.entries(((detail.submission as Row)?.answers||{}) as Row).map(([key,value],index)=><article key={key}><h4>Question {index+1}</h4><ResponseValue value={value}/></article>)}</section>{rows((detail.submission as Row)?.automaticFeedback).map((f,i)=><article key={i}><b>Question {i+1}: {s(f.earned)}/{s(f.available)}</b><p>{s(f.feedback)}</p><p>{s(f.learnerAdvice)}</p>{rows(f.criteria).map((c,j)=><p key={j}>{s(c.criterion)}: {s(c.score)}/{s(c.maximum)} · {s(c.feedback)}</p>)}</article>)}{rows(detail.history).map(h=><p key={s(h.id)}>{when(h.created_at)} · {s(h.previous_score)} → {s(h.new_score)} · {s(h.reason)}</p>)}{rows(detail.appeals).map(a=><p key={s(a.id)}>Appeal: {s(a.status)} · {s(a.reason)} · {s(a.response)}</p>)}</>}</details>;}
function downloadSessionCalendar(session:Row) {const date=(v:unknown)=>new Date(s(v)).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const escape=(v:unknown)=>s(v).replaceAll("\\","\\\\").replaceAll("\n","\\n").replaceAll(",","\\,").replaceAll(";","\\;");const calendar=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//UCC Growth+//Learning//EN","BEGIN:VEVENT",`UID:ucc-session-${session.id}@growthplus`,`DTSTAMP:${date(new Date().toISOString())}`,`DTSTART:${date(session.starts_at)}`,`DTEND:${date(session.ends_at)}`,`SUMMARY:${escape(session.title)}`,`URL:${s(session.meeting_url)}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");const url=URL.createObjectURL(new Blob([calendar],{type:"text/calendar"})),a=document.createElement("a");a.href=url;a.download=`ucc-session-${session.id}.ics`;a.click();URL.revokeObjectURL(url);}

export function SupportWorkspace({role}:{role:string}) {const [data,setData]=useState<Row>({}),[category,setCategory]=useState("technical"),[message,setMessage]=useState(""),[error,setError]=useState("");const load=useCallback(()=>jsonRequest("/api/support").then(setData).catch(e=>setError(e.message)),[]);useEffect(()=>{void load();},[load]);return <section className="delivery-workspace"><p>{s(data.responseTarget)}</p><form className="delivery-form" onSubmit={async e=>{e.preventDefault();try{await jsonRequest("/api/support",{category,message});setMessage("");await load();}catch(err){setError(err instanceof Error?err.message:"Could not submit.");}}}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{["technical","learning","assessment","payment","access"].map(v=><option key={v}>{v}</option>)}</select></label><label>Describe the issue<textarea minLength={10} value={message} onChange={e=>setMessage(e.target.value)} required/></label><button>Open support ticket</button></form>{error&&<p role="alert">{error}</p>}{rows(data.tickets).map(ticket=><details key={s(ticket.id)}><summary>{s(ticket.reference)} · {s(ticket.category)} · {s(ticket.status)}</summary><p>{s(ticket.message)}</p>{rows(ticket.replies).map(reply=><article key={s(reply.id)}><b>{s(reply.author_name)} · {when(reply.created_at)}</b><p>{s(reply.message)}</p></article>)}<SupportReply id={Number(ticket.id)} role={role} onSaved={()=>void load()}/></details>)}</section>;}
function SupportReply({id,role,onSaved}:{id:number;role:string;onSaved:()=>void}) {const [message,setMessage]=useState(""),[status,setStatus]=useState("in_progress");return <form className="delivery-form" onSubmit={async e=>{e.preventDefault();try{await jsonRequest("/api/support",{id,message,status},"PATCH");setMessage("");onSaved();}catch(err){toast.error(err instanceof Error?err.message:"Could not reply.");}}}><label>Reply<textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={3} required/></label>{role==="admin"&&<label>Ticket status<select value={status} onChange={e=>setStatus(e.target.value)}>{["open","in_progress","resolved","closed"].map(v=><option key={v}>{v}</option>)}</select></label>}<button>Send reply</button></form>;}

export function DeliveryCourseSettings({design,onChange,activities}:{design:CourseDesign;onChange:(design:CourseDesign)=>void;activities:{id:string;title:string;kind:string}[]}) {const policy=normalizeDeliveryPolicy(design.delivery),set=(key:string,value:unknown)=>onChange({...design,delivery:normalizeDeliveryPolicy({...policy,[key]:value})});return <section className="delivery-settings"><h3>Delivery and award requirements</h3><div className="delivery-form"><label>Identity verification<select value={policy.identityRequired} onChange={e=>set("identityRequired",e.target.value)}><option value="before_award">Before issuing the award</option><option value="before_learning">Before starting learning</option></select></label><label>Final assessment marking<select value={policy.markingMode} onChange={e=>set("markingMode",e.target.value)}><option value="automatic">Automatic grading</option><option value="human">Human marking</option><option value="assisted">AI draft, then marker approval</option></select></label><label>Assessment deadline (local time)<input type="datetime-local" value={policy.assessmentDueAt?new Date(Date.parse(policy.assessmentDueAt)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):""} onChange={e=>set("assessmentDueAt",e.target.value?new Date(e.target.value).toISOString():"")}/></label><label>Feedback target in days<input type="number" min={1} max={60} value={policy.feedbackDays} onChange={e=>set("feedbackDays",Number(e.target.value))}/></label>{!assessmentRequired(design.certificate.awardType)&&<label>Attendance required (%)<input type="number" min={0} max={100} value={policy.attendancePercent} onChange={e=>set("attendancePercent",Number(e.target.value))}/></label>}<label>Refund request window in days<input type="number" min={0} max={90} value={policy.refundDays} onChange={e=>set("refundDays",Number(e.target.value))}/></label><label>Published refund terms<textarea value={policy.refundPolicy} onChange={e=>set("refundPolicy",e.target.value)}/></label></div><fieldset><legend>Additional practicals required for this award</legend>{activities.filter(a=>a.kind!=="inline").map(a=><label key={a.id}><input type="checkbox" checked={policy.requiredPracticalIds.includes(a.id)} onChange={e=>set("requiredPracticalIds",e.target.checked?[...policy.requiredPracticalIds,a.id]:policy.requiredPracticalIds.filter(id=>id!==a.id))}/>{a.title}</label>)}</fieldset><p>These settings form part of the approved course design. Published-course changes follow the existing amendment process.</p></section>;}

export function StudioRecovery({draftKey,value,onRestore}:{draftKey:string;value:Row;onRestore:(value:Row)=>void}) {const [saved,setSaved]=useState(""),[recovery,setRecovery]=useState<Row|null>(null),ready=useRef(false);useEffect(()=>{ready.current=false;void jsonRequest("/api/delivery?area=recovery").then(data=>{const row=rows(data.items).find(r=>r.draft_key===draftKey);if(row)setRecovery(JSON.parse(s(row.payload_json)) as Row);ready.current=true;}).catch(()=>{ready.current=true;});},[draftKey]);const serialized=JSON.stringify(value);useEffect(()=>{if(!ready.current)return;setSaved("Unsaved changes");const timer=setTimeout(()=>{void jsonRequest("/api/delivery",{action:"recovery",key:draftKey,value:JSON.parse(serialized)}).then(()=>setSaved(`Recovery saved at ${new Date().toLocaleTimeString()}`)).catch(()=>setSaved("Recovery could not save. Keep this page open or save the draft."));},1500);return()=>clearTimeout(timer);},[serialized,draftKey]);useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(saved.startsWith("Unsaved")||saved.startsWith("Recovery could")){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[saved]);return <div className="studio-recovery"><span role="status">{saved||"Draft recovery ready"}</span>{recovery&&<button onClick={()=>{onRestore(recovery);setRecovery(null);}}>Restore saved working copy</button>}</div>;}

export function LearnerCourseTools({code,materialId}:{code:string;materialId?:string}) {const [note,setNote]=useState(""),[bookmark,setBookmark]=useState(false),[state,setState]=useState(""),[loaded,setLoaded]=useState(false),[record,setRecord]=useState<Row|null>(null),[bookmarks,setBookmarks]=useState<Row[]>([]);const key=`note:${materialId||"course"}`;useEffect(()=>{setLoaded(false);void jsonRequest(`/api/delivery?area=workspace&courseCode=${encodeURIComponent(code)}`).then(data=>{const items=rows(data.items);setBookmarks(items.filter(r=>s(r.item_key).startsWith("bookmark:")&&r.value));setNote(s(items.find(r=>r.item_key===key)?.value));setBookmark(Boolean(items.find(r=>r.item_key===`bookmark:${materialId}`)?.value));setLoaded(true);}).catch(()=>setState("Notes could not load."));void jsonRequest(`/api/delivery?area=overview`).then(data=>setRecord(rows(data.records).find(r=>r.courseCode===code)??null));},[code,key,materialId]);useEffect(()=>{if(!loaded)return;const timer=setTimeout(()=>{void saveWorkspace(code,key,note).then(()=>setState("Notes saved")).catch(()=>setState("Notes could not save. Try again."));},1000);return()=>clearTimeout(timer);},[note,code,key,loaded]);return <aside className="learner-tools"><details><summary>Notes, bookmark and achievement record</summary><label>Private lesson notes<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><small role="status">{state}</small>{bookmarks.map(bookmark=><a key={s(bookmark.item_key)} href={`/learn/${encodeURIComponent(code)}/${encodeURIComponent(s(bookmark.item_key).slice(9))}`}>Saved lesson: {s(bookmark.item_key).slice(9)}</a>)}{materialId&&<button onClick={async()=>{try{await saveWorkspace(code,`bookmark:${materialId}`,!bookmark);setBookmark(!bookmark);}catch(error){toast.error(error instanceof Error?error.message:"Could not save bookmark.");}}}>{bookmark?"Remove bookmark":"Bookmark lesson"}</button>}<a href={`/?view=discussions&courseCode=${encodeURIComponent(code)}`}>Ask the course community</a>{rows(record?.requirements).map(requirement=><p key={s(requirement.id)}>{requirement.complete?<CheckCircle2 size={15}/>:"○"} {s(requirement.label)}<small>{s(requirement.evidence)}</small></p>)}<ActionForm action="evaluation" courseCode={code} fields={[{key:"rating",label:"Course rating",options:["1","2","3","4","5"]},{key:"feedback",label:"Course feedback",type:"textarea",required:false}]} onSaved={()=>toast.success("Course evaluation saved")} label="Submit evaluation"/></details></aside>;}

function EvidenceQueue({courseCode}:{courseCode:string}) {
  const [items,setItems]=useState<Row[]>([]),[filter,setFilter]=useState("pending"),[nextOffset,setNextOffset]=useState<number|null>(null);
  const load=useCallback(async()=>{try{const data=await jsonRequest(`/api/delivery/evidence?courseCode=${encodeURIComponent(courseCode)}&filter=${filter}`);setItems(rows(data.items));setNextOffset(data.nextOffset==null?null:Number(data.nextOffset));}catch(e){toast.error(e instanceof Error?e.message:"Evidence could not load.");}},[courseCode,filter]);
  useEffect(()=>{void load();},[load]);
  return <section><h3>Practical and lesson evidence queue</h3><label>Show evidence<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Awaiting grading</option><option value="all">All decisions</option></select></label>{items.map(row=><EvidenceDecision key={`${row.type}-${row.id}`} row={row} onSaved={()=>void load()}/>)}{!items.length&&<p>No evidence in this queue.</p>}{nextOffset!=null&&<button onClick={async()=>{try{const data=await jsonRequest(`/api/delivery/evidence?courseCode=${encodeURIComponent(courseCode)}&filter=${filter}&offset=${nextOffset}`);setItems([...items,...rows(data.items)]);setNextOffset(data.nextOffset==null?null:Number(data.nextOffset));}catch(e){toast.error(e instanceof Error?e.message:"Evidence could not load.");}}}>Load more evidence</button>}</section>;
}
function ResponseValue({value}:{value:unknown}) {
  if (value==null || value==="") return <span>No response recorded.</span>;
  if (Array.isArray(value)) return <ol>{value.map((item,i)=><li key={i}><ResponseValue value={item}/></li>)}</ol>;
  if (typeof value==="object") return <dl>{Object.entries(value as Row).map(([key,item])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd><ResponseValue value={item}/></dd></div>)}</dl>;
  return <span style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{s(value)}</span>;
}
function EvidenceDecision({row,onSaved}:{row:Row;onSaved:()=>void}) {
  const [detail,setDetail]=useState<Row|null>(null),[mark,setMark]=useState(""),[feedback,setFeedback]=useState(""),[decision,setDecision]=useState("assessed"),[busy,setBusy]=useState(false);
  const record=(detail?.record||{}) as Row;
  const parse=(value:unknown)=>{try{return JSON.parse(s(value));}catch{return value;}};
  return <details onToggle={e=>{if(e.currentTarget.open&&!detail)void jsonRequest(`/api/delivery/evidence?type=${row.type}&id=${row.id}`).then(setDetail).catch(error=>toast.error(error.message));}}><summary>{s(row.learner_email)} · {s(record.title||row.title)} · {s(row.status).replaceAll("_"," ")}</summary>{detail&&<section className="delivery-evidence"><p>Submitted {when(record.submitted_at)} · Attempt {s(record.attempt_number)} · Pass threshold {s(record.pass_mark)}%</p>{record.instructions?<p>{s(record.instructions)}</p>:null}{record.rubric?<details><summary>Approved marking rubric</summary><p style={{whiteSpace:"pre-wrap"}}>{s(record.rubric)}</p></details>:null}{record.response_text||record.report?<><h4>Learner response</h4><ResponseValue value={record.response_text||record.report}/></>:null}{record.answers_json?<><h4>Practical answers</h4><ResponseValue value={parse(record.answers_json)}/></>:null}{record.observations_json?<><h4>Practical observations</h4><ResponseValue value={parse(record.observations_json)}/></>:null}{record.notebook_url&&s(record.notebook_url).startsWith("https://")?<a href={s(record.notebook_url)} target="_blank" rel="noopener noreferrer">Open submitted notebook</a>:null}{record.evidence_key||record.notebook_key?<a href={`/api/delivery/evidence?type=${row.type}&id=${row.id}&download=1`}>Download {s(record.evidence_file_name||record.notebook_file_name)||"submitted evidence"}</a>:null}{record.feedback?<><h4>Current feedback</h4><p>{s(record.feedback)}</p></>:null}{rows(detail.history).length>0&&<details><summary>Decision history</summary>{rows(detail.history).map(h=><p key={s(h.id)}>{when(h.created_at)} · {s(h.reason)}</p>)}</details>}</section>}<form className="delivery-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await jsonRequest("/api/delivery/evidence",{type:row.type,id:row.id,mark:Number(mark),feedback,decision},"PATCH");setDetail(null);onSaved();toast.success("Practical decision recorded");}catch(err){toast.error(err instanceof Error?err.message:"Decision could not save.");}finally{setBusy(false);}}}><label>Mark<input type="number" min={0} max={Number(record.max_mark)||Number(row.max_mark)||100} value={mark} onChange={e=>setMark(e.target.value)} required/></label><label>Feedback<textarea minLength={10} value={feedback} onChange={e=>setFeedback(e.target.value)} required/></label><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="assessed">Final result</option><option value="resubmit">Resubmit</option></select></label><button disabled={busy}>{busy?"Saving…":"Record decision"}</button></form><button onClick={async()=>{try{await jsonRequest("/api/delivery/evidence",{type:row.type,id:row.id,retry:true},"PATCH");onSaved();}catch(e){toast.error(e instanceof Error?e.message:"Retry failed.");}}}>Retry failed automatic grading</button></details>;
}
