"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import type { StructuredLearningActivity } from "@/lib/structured-learning-activities";
import type { CourseMaterialRecord } from "@/lib/course-design";
import { externalActivityIssues } from "@/lib/lti-types";
import { ExternalActivityPlayer } from "./external-activity-player";
type Tool = { id: string; name: string; deepLinkAvailable: boolean; defaultLaunchUrl: string };
export function ExternalActivityAuthor({ courseCode, lesson, existing, onApply }: { courseCode: string; lesson?: CourseMaterialRecord; existing?: StructuredLearningActivity; onApply: (activity: StructuredLearningActivity) => void }) {
  const [tools, setTools] = useState<Tool[]>([]), [toolId, setToolId] = useState(""), [url, setUrl] = useState(""), [title, setTitle] = useState("External interactive practice"), [instructions, setInstructions] = useState("Complete the activity, review its feedback and return to this lesson."), [custom, setCustom] = useState(""), [selectionId, setSelectionId] = useState(""), [error, setError] = useState("");
  useEffect(() => { void fetch("/api/lti/tools").then(r => r.json()).then(d => { const available = (d.tools || []).map((t: Tool & { redirect_uris_json?: string; deep_link_url?: string }) => ({ ...t, deepLinkAvailable: t.deepLinkAvailable ?? Boolean(t.deep_link_url), defaultLaunchUrl: t.defaultLaunchUrl || JSON.parse(t.redirect_uris_json || "[]")[0] })); setTools(available); }).catch(() => setError("The registered tool list could not load.")); }, []);
  useEffect(() => { if (!selectionId) return; let cancelled = false; const refresh = async () => { try { const r = await fetch(`/api/lti/content-selections?id=${encodeURIComponent(selectionId)}`), d = await r.json(); if (cancelled) return; if (d.result) { setToolId(d.result.lti.toolId); setUrl(d.result.lti.launchUrl); setCustom(JSON.stringify(d.result.lti.custom, null, 2)); setTitle(d.result.title); setInstructions(d.result.instructions); setSelectionId(""); toast.success("Activity selected. Review it before applying."); } else if (d.expired) { setSelectionId(""); setError("Content selection expired. Open the tool again."); } } catch {} }; void refresh(); const timer = setInterval(() => void refresh(), 2500); return () => { cancelled = true; clearInterval(timer); }; }, [selectionId]);
  let parameters: Record<string, string> = {}, parameterError = "";
  try { parameters = custom.trim() ? JSON.parse(custom) : {}; if (!parameters || typeof parameters !== "object" || Array.isArray(parameters) || Object.values(parameters).some(v => typeof v !== "string")) throw new Error(); } catch { parameterError = "Custom parameters must be a JSON object containing text values."; }
  const activity: StructuredLearningActivity = { ...existing, id: existing?.id || "external-preview", kind: "inline", title, instructions, required: existing?.required ?? false, passMark: existing?.passMark ?? 60, attemptsAllowed: existing?.attemptsAllowed ?? 3, maxMark: existing?.maxMark ?? 100, materialId: lesson?.id, sectionId: lesson?.sectionId, sectionTitle: lesson?.sectionTitle, gradingMode: "lti", interactive: undefined, lti: { toolId, launchUrl: url, custom: parameters } };
  const issues = [...externalActivityIssues(activity.lti), ...(parameterError ? [parameterError] : []), ...(!title.trim() || !instructions.trim() ? ["Add the activity title and instructions."] : [])];
  const selectContent = async () => { const tab = window.open("about:blank", "_blank"); if (!tab) return setError("Allow the content selector to open in a new tab."); tab.opener = null; setError(""); try { const r = await fetch("/api/lti/launch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ courseCode, toolId, deepLink: true }) }), d = await r.json(); if (!r.ok) throw new Error(d.error); setSelectionId(d.selectionId); tab.location.href = d.url; } catch (e) { tab.close(); setError(e instanceof Error ? e.message : "Content selector unavailable."); } };
  return <details className="studio-external-author"><summary>Add H5P or another connected activity</summary><p>Choose a tool registered by the administrator. Select content inside the tool or enter its LTI activity launch URL. Results return to this course.</p>{!tools.length && <p>No external tool has been registered. Ask the administrator to add the institution’s H5P or LTI connection under Programme governance.</p>}<label>Connected tool<select value={toolId} onChange={e => { setToolId(e.target.value); setUrl(tools.find(t => t.id === e.target.value)?.defaultLaunchUrl || ""); }}><option value="">Choose a registered tool</option>{tools.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{tools.find(t => t.id === toolId)?.deepLinkAvailable && <button type="button" disabled={Boolean(selectionId)} onClick={() => void selectContent()}>{selectionId ? "Waiting for content selection" : "Select content in the connected tool"}</button>}{existing?.lti && <button type="button" onClick={() => { setToolId(existing.lti!.toolId); setUrl(existing.lti!.launchUrl); setTitle(existing.title); setInstructions(existing.instructions); setCustom(JSON.stringify(existing.lti!.custom, null, 2)); }}>Load this lesson’s external activity</button>}<label>Connected activity title<input value={title} onChange={e => setTitle(e.target.value)} /></label><label>Activity launch URL<input type="url" value={url} onChange={e => setUrl(e.target.value)} placeholder="The activity’s LTI launch URL" /></label><label>Connected activity instructions<textarea value={instructions} onChange={e => setInstructions(e.target.value)} /></label><details><summary>Optional tool parameters</summary><label>Custom parameters<textarea value={custom} onChange={e => setCustom(e.target.value)} placeholder={'{"content_id": "123"}'} /></label></details>{(error || issues.length > 0) && <p role="status">{error || issues.join(" ")}</p>}{issues.length === 0 && <ExternalActivityPlayer courseCode={courseCode} activity={activity} preview />}<p>Practice is optional initially. Use the lesson editor to set its pass mark and whether it is required. External attempt limits are managed in the connected tool.</p><button type="button" disabled={!lesson || issues.length > 0} onClick={() => { onApply({ ...activity, id: existing?.id || crypto.randomUUID() }); toast.success("Connected activity applied. Review and save the course."); }}>Apply connected activity to lesson</button></details>;
}
