"use client";
import { useState } from "react";
import { interactiveLabels, type InteractiveActivity, type InteractiveResponse } from "@/lib/interactive-activities";
export function InteractivePlayer({activity,value,onChange}:{activity:InteractiveActivity;value:string;onChange:(value:string)=>void}) {
  const [revealed,setRevealed]=useState<string[]>([]);
  let response:InteractiveResponse={};try{response=JSON.parse(value||"{}");}catch{}
  const update=(part:Partial<InteractiveResponse>)=>onChange(JSON.stringify({...response,...part}));
  const order=response.order?.length===activity.items.length?response.order:[...activity.items].sort((a,b)=>a.prompt.localeCompare(b.prompt)).map(i=>i.id);
  const move=(index:number,delta:number)=>{const next=[...order];[next[index],next[index+delta]]=[next[index+delta],next[index]];update({order:next});};
  return <div className="native-practice"><h4>{interactiveLabels[activity.kind]}</h4>{activity.kind==="sequencing"?<><p>Put the steps in order. Use the Move up and Move down buttons with a keyboard or touch.</p><ol>{order.map((id,index)=><li key={id}><span>{activity.items.find(i=>i.id===id)?.prompt}</span><button type="button" aria-label={`Move step ${index+1} up`} disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button type="button" aria-label={`Move step ${index+1} down`} disabled={index===order.length-1} onClick={()=>move(index,1)}>Move down</button></li>)}</ol><button type="button" onClick={()=>update({order})}>Confirm this order</button></>:activity.items.map((item,index)=><fieldset key={item.id}><legend>{index+1}. {item.prompt}</legend>{activity.kind==="flashcards"?<><button type="button" aria-expanded={revealed.includes(item.id)} onClick={()=>{setRevealed(ids=>ids.includes(item.id)?ids.filter(id=>id!==item.id):[...ids,item.id]);update({reviewed:[...new Set([...(response.reviewed||[]),item.id])]});}}>{revealed.includes(item.id)?"Hide answer":"Reveal answer"}</button>{revealed.includes(item.id)&&<div><p>{item.answer}</p><small>{item.explanation}</small></div>}{response.reviewed?.includes(item.id)&&<span> Reviewed</span>}</>:activity.kind==="matching"?<label>Choose the matching answer<select value={response.selections?.[item.id]||""} onChange={e=>update({selections:{...response.selections,[item.id]:e.target.value}})}><option value="">Choose a match</option>{item.choices.map(choice=><option key={choice}>{choice}</option>)}</select></label>:item.choices.map((choice,n)=><label className="native-choice" key={choice}><input type="radio" name={`native-${item.id}`} checked={response.selections?.[item.id]===choice} onChange={()=>update({selections:{...response.selections,[item.id]:choice}})}/><span>{String.fromCharCode(65+n)}. {choice}</span></label>)}</fieldset>)}<p aria-live="polite">{activity.kind==="flashcards"?`${response.reviewed?.length||0} of ${activity.items.length} cards reviewed`:activity.kind==="sequencing"?"Confirm the order before submitting.":`${Object.keys(response.selections||{}).length} of ${activity.items.length} items answered`}</p></div>;
}
