"use client";
import { useEffect, useState } from "react";
import type { AiVerification } from "@/lib/course-ai-verification";
type Result = { id: string; state: string; createdAt: string; error?: string; verification?: AiVerification; provider?: string; model?: string };
type Status = { available: boolean; providers: { id: string; label: string; model: string; configured: boolean }[]; results: Result[] };
export function LiveAiVerification() {
  const [status, setStatus] = useState<Status | null>(null), [provider, setProvider] = useState("auto"), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { let cancelled = false; const load = async () => { try { const r = await fetch("/api/course-ai/verify"); if (!r.ok) return; const d = await r.json(); if (!cancelled) { setStatus(d); setBusy(d.results?.some((j: Result) => ["queued", "running"].includes(j.state)) || false); } } catch {} }; void load(); const timer = setInterval(() => void load(), 5000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  if (!status) return null;
  const verify = async () => { setBusy(true); setError(""); try { const r = await fetch("/api/course-ai/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider }) }), d = await r.json(); if (!r.ok) throw new Error(d.error); } catch (e) { setBusy(false); setError(e instanceof Error ? e.message : "Verification could not start."); } };
  return <details className="studio-tools live-ai-verification"><summary>Live AI verification</summary><p>Run a real, small teaching task through the configured provider. The diagnostic checks lesson text, answer keys, native practice, outcome links and source excerpts. It uses the normal daily allowance and never applies its draft to a course.</p><label>Verification provider<select value={provider} onChange={e => setProvider(e.target.value)}><option value="auto">Automatic</option>{status.providers.map(p => <option key={p.id} value={p.id} disabled={!p.configured}>{p.label} · {p.configured ? p.model : "not configured"}</option>)}</select></label>{!status.available && <p>No AI provider is configured on this deployment. Add the server credentials, then run this diagnostic.</p>}<button type="button" disabled={!status.available || busy} onClick={() => void verify()}>{busy ? "Live verification in progress" : "Run live AI verification"}</button>{error && <p role="alert">{error}</p>}{status.results.map(result => <article className="studio-verification-result" key={result.id}><h4>{result.verification?.status === "passed" ? "Provider and quality checks passed" : result.verification ? "Provider responded, quality review required" : result.state === "failed" ? "Live request failed" : "Verification in progress"}</h4><p>{result.createdAt} {result.provider && `· ${result.provider} · ${result.model}`}{result.verification && ` · ${(result.verification.latencyMs / 1000).toFixed(1)} seconds`}</p>{result.error && <p role="alert">{result.error}</p>}{result.verification && <ul>{result.verification.checks.map(check => <li key={check.label}>{check.passed ? "Passed" : "Review"}: {check.label}</li>)}</ul>}</article>)}</details>;
}
