import './seed-commercial-test';
import { getRawDb } from '../src/db/raw';
import { defaultCourseDesign } from '../src/lib/course-design';
import { enrolWithSnapshot } from '../src/lib/course-access';
import type { InteractiveActivity } from '../src/lib/interactive-activities';
const db=getRawDb();const design=defaultCourseDesign();design.delivery.markingMode='human';
const items=[{id:'a',prompt:'What supports a decision?',choices:['Evidence','Guesswork'],answer:'Evidence',explanation:'Use reliable evidence.'},{id:'b',prompt:'What follows checking evidence?',choices:['Review','Ignore'],answer:'Review',explanation:'Review the relevant criteria.'}];
const kinds=['knowledge_check','matching','sequencing','flashcards','scenario'] as const;
const materials=kinds.map(kind=>({id:`native-${kind}`,title:`Practice ${kind}`,kind:'Read',source:'Test author',readableHtml:`<h2>Practice ${kind}</h2><p>Use the interactive controls to complete the practice.</p>`,sectionId:'section-1',sectionTitle:'Interactive practice',outcomeIds:['outcome-1'],accessibilityChecked:true,required:true}));
const activities=kinds.map(kind=>({id:kind,kind:'inline',title:`Native ${kind}`,instructions:'Complete every item and review the feedback.',materialId:`native-${kind}`,sectionId:'section-1',required:true,passMark:60,attemptsAllowed:3,maxMark:100,gradingMode:'rule',responseType:'long_text',interactive:{kind,items,...(kind==='sequencing'?{order:['b','a']}:{})} as InteractiveActivity}));
await db.prepare("INSERT INTO course_drafts(code,title,status,created_by_email,design_json,materials_json,activities_json,assessment_config_json,certificate_preapproved) VALUES('E2E-NATIVE','Native interactive authoring and practice','active','owner@example.test',?,?,?,?,1)").bind(JSON.stringify(design),JSON.stringify(materials),JSON.stringify(activities),JSON.stringify({passMark:60,attempts:'3',questions:[{id:'final',type:'Multiple choice',prompt:'What supports decisions?',options:['Evidence','Guesswork'],correctAnswer:'Evidence',points:1,approved:true,previewed:true,gradingMode:'rule',outcomeIds:['outcome-1']}]})).run();
enrolWithSnapshot('learner@example.test','E2E-NATIVE');
console.log(JSON.stringify({nativeSeeded:true}));

// Deterministic authoring previews, never a live AI call.
const {normalizePlan}=await import('../src/lib/course-ai');
const {ensureAiTables}=await import('../src/lib/course-ai-jobs');ensureAiTables();
const raw={title:'Procurement evidence and responsible decisions',discipline:'Business',description:'A practical programme for Ghanaian procurement officers to check evidence, apply criteria and make responsible decisions.',intendedAudience:'Procurement officers in Ghana',prerequisites:'Basic procurement experience',accessibilityStatement:'Readable text and keyboard practice',category:'professional',deliveryPattern:'asynchronous',level:'applied',language:'English',expectedHours:12,objectives:['Evaluate procurement evidence','Apply published procurement criteria'],skills:['Evidence appraisal'],outcomes:[{statement:'Evaluate evidence for procurement decisions.',skill:'Appraisal',assessmentMethod:'Case analysis'},{statement:'Apply published procurement criteria.',skill:'Application',assessmentMethod:'Knowledge check'}],sections:[{title:'Evaluate evidence',description:'Check evidence before making a decision.',lessonHtml:'<h2>Check the evidence</h2><p>Verify the source before deciding.</p>',estimatedMinutes:10,activityTitle:'Evidence practice',activityInstructions:'Complete the evidence practice.',videoSearchQuery:'procurement evidence',openResourceQuery:'procurement evidence',outcomeIndexes:[0],alignmentReason:'The lesson explains source verification needed to evaluate evidence.',sourceExcerpt:'Verify the source before deciding.',interactive:{kind:'knowledge_check',items,order:[]}},{title:'Apply criteria',description:'Use the published criteria.',lessonHtml:'<h2>Apply published criteria</h2><p>Apply the published procurement criteria consistently.</p>',estimatedMinutes:10,activityTitle:'Criteria practice',activityInstructions:'Review the criteria practice.',videoSearchQuery:'procurement criteria',openResourceQuery:'procurement criteria',outcomeIndexes:[1],alignmentReason:'This lesson teaches the application of published criteria.',sourceExcerpt:'',interactive:{kind:'flashcards',items,order:[]}}],assessmentQuestions:[{type:'Multiple choice',prompt:'What should support a procurement decision?',options:['Evidence','Guesswork'],correctAnswer:'Unmatched answer',points:1,scheme:'One mark for evidence.',feedbackCorrect:'Use reliable evidence.',feedbackIncorrect:'Check the evidence.',learnerAdvice:'Review the source.',outcomeIndexes:[0]}],warnings:['Simulated provider fixture for browser acceptance.']};
for(const stage of ['outline','lessons'] as const){const input={mode:'idea' as const,stage,provider:'openai' as const,sourceText:'Verify the source before deciding.',sectionCount:2};const p=normalizePlan({plan:raw as Parameters<typeof normalizePlan>[0]['plan'],provider:'openai',model:'simulated-provider',usage:{inputTokens:25,outputTokens:50}},input);await db.prepare("INSERT INTO course_ai_jobs(id,owner_email,input_json,status,proposal_json,created_at) VALUES(?, 'owner@example.test',?,'completed',?,'2020-01-01 00:00:00')").bind(`simulated-${stage}`,JSON.stringify(input),JSON.stringify(p)).run();}
